/* ============================================================
   Stadt-Daten für die SEO-Landingpages (/roboter-mieten/<slug>/).
   30 größte Städte Deutschlands. Pro Stadt UNIQUE Content:
   intro (Hero-Lead), scene (Event-Landschaft), venues (Locations),
   faqLoc (stadtspezifische FAQ-Antwort), nearby (interne Links).
   Generator: tools/seo/generate.mjs
   ============================================================ */
export const CITIES = [
  {
    slug: 'berlin', name: 'Berlin', state: 'Berlin', pop: '3,9 Mio.',
    intro: 'Hauptstadt, Startup-Metropole, Messestandort: Nirgendwo in Deutschland finden mehr Konferenzen, Produktlaunches und Tech-Events statt als in Berlin. Genau hier hält Ludwig II. besonders oft Hof — ein humanoider Event-Roboter, der Ihren Auftritt zum Gesprächsthema der Stadt macht.',
    scene: 'Ob IFA, ITB oder InnoTrans auf dem Berliner Messegelände, ein Kongress im CityCube, eine Konferenz in der STATION Berlin oder ein Firmenevent im Estrel: Berlin ist die dichteste Eventlandschaft des Landes — und zugleich die, in der Aufmerksamkeit am härtesten umkämpft ist. Ein humanoider Roboter mit Krone und Umhang durchbricht das Grundrauschen aus Ständen, Screens und Give-aways in Sekunden. Für Berliner Startups, Agenturen und Konzerne ist Ludwig der Standmagnet, der Besucherströme umlenkt.',
    venues: [
      { n: 'Messe Berlin / CityCube', d: 'IFA, ITB, InnoTrans & Co. — Ludwig zieht Besucher an Ihren Stand, statt dass sie vorbeilaufen.' },
      { n: 'STATION Berlin & bcc', d: 'Tech-Konferenzen und Kongresse: der Roboter als Eröffnungsmoment oder Foyer-Attraktion.' },
      { n: 'Estrel Congress Center', d: 'Galas und Firmenfeiern in Europas größtem Convention-Hotel — royaler Empfang inklusive.' },
      { n: 'Showrooms & Flagship-Stores', d: 'Store-Eröffnungen von Mitte bis Ku’damm: Laufkundschaft bleibt stehen, filmt und teilt.' },
    ],
    faqLoc: 'Praktisch überall: Messegelände (Messe Berlin, CityCube), Kongresszentren (bcc, Estrel), Eventlocations wie STATION Berlin, Hotels, Showrooms und Stores. Wichtig sind nur eine ebene Fläche, Strom und Internet — das klären wir bei der Planung.',
    nearby: ['leipzig', 'dresden', 'hamburg', 'hannover'],
  },
  {
    slug: 'hamburg', name: 'Hamburg', state: 'Hamburg', pop: '1,9 Mio.',
    intro: 'Hafenstadt, Medienstandort, OMR-Heimat: Hamburg liebt große Auftritte. Mit Ludwig II. mieten Sie einen humanoiden Event-Roboter, der auf Messen, Konferenzen und Firmenevents in Hamburg genau das liefert — Aufmerksamkeit, die man nicht buchen kann. Außer bei uns.',
    scene: 'Von der WindEnergy und SMM in den Hamburger Messehallen über Kongresse im frisch modernisierten CCH bis zum OMR Festival, das jedes Jahr die halbe Digitalbranche in die Stadt holt: Hamburgs Eventkalender ist prall gefüllt. Wer hier auffallen will, braucht mehr als ein Roll-up. Ein königlicher Roboter, der Gäste begrüßt, Small Talk führt und für virale Clips sorgt, macht Ihren Stand oder Ihre Feier zum Anziehungspunkt — von der HafenCity bis zur Speicherstadt.',
    venues: [
      { n: 'Hamburg Messe und Congress', d: 'WindEnergy, SMM, INTERNORGA — Ludwig verwandelt Ihren Messestand in den meistfotografierten der Halle.' },
      { n: 'CCH — Congress Center Hamburg', d: 'Eines der größten Kongresszentren Europas: der Roboter als Keynote-Highlight oder Empfangschef.' },
      { n: 'OMR & Digital-Events', d: 'Wo alle um Aufmerksamkeit kämpfen, gewinnt der einzige König im Raum.' },
      { n: 'HafenCity, Speicherstadt & Elbufer', d: 'Produktlaunches und Firmenfeiern mit Hafenkulisse — royaler Auftritt vor maritimer Bühne.' },
    ],
    faqLoc: 'Vom Messegelände (Hamburg Messe, CCH) über Eventlocations in HafenCity und Speicherstadt bis zu Hotels, Agentur-Events und Store-Eröffnungen. Benötigt werden nur ebene Fläche, Strom und Internet — Details klären wir vorab.',
    nearby: ['bremen', 'kiel', 'hannover', 'berlin'],
  },
  {
    slug: 'muenchen', name: 'München', state: 'Bayern', pop: '1,6 Mio.',
    intro: 'Ausgerechnet in der Stadt des echten Königs Ludwig II. tritt sein robotischer Namensvetter an: Auf Messen wie der automatica, auf Konferenzen und Firmenevents in München sorgt der humanoide Event-Roboter für Auftritte, über die noch beim Weißwurstfrühstück gesprochen wird.',
    scene: 'München ist Deutschlands Bühne für Zukunftstechnologie: bauma, ISPO, EXPO REAL, electronica — und mit der automatica gleich die Weltleitmesse für Robotik und Automation. Ein humanoider Roboter ist hier kein Fremdkörper, sondern der logische nächste Schritt für jeden Messestand, der Innovationskraft zeigen will. Dazu kommen Kongresse im ICM, Firmenevents zwischen BMW Welt und Werksviertel und Premium-Feiern, für die München berühmt ist. Ludwig II. — der Name ist in Bayern schließlich Programm.',
    venues: [
      { n: 'Messe München / ICM', d: 'bauma, automatica, EXPO REAL, electronica — Ihr Stand bekommt den König, die Konkurrenz die Restaufmerksamkeit.' },
      { n: 'MOC & Zenith / Werksviertel', d: 'Produktlaunches und Brand-Events in Münchens Kreativarealen — mit royalem Überraschungsmoment.' },
      { n: 'BMW Welt & Automotive-Events', d: 'Wo Technik inszeniert wird, gehört ein humanoider Roboter auf die Bühne.' },
      { n: 'Hotels & Premium-Locations', d: 'Galas, Jubiläen und exklusive Feiern von Maximilianstraße bis Schwabing — königlich empfangen.' },
    ],
    faqLoc: 'Überall dort, wo Events stattfinden: Messe München und ICM, MOC, Zenith und Werksviertel, Hotels und Ballsäle, Showrooms und Stores in der Innenstadt. Voraussetzungen sind lediglich ebene Fläche, Strom und Internet.',
    nearby: ['augsburg', 'nuernberg', 'stuttgart', 'salzburg'],
  },
  {
    slug: 'koeln', name: 'Köln', state: 'Nordrhein-Westfalen', pop: '1,1 Mio.',
    intro: 'gamescom, Anuga, DMEXCO: Köln ist Messe- und Medienstadt — und ein Publikum, das Entertainment im Blut hat. Ein humanoider Event-Roboter, der Gäste begrüßt, Witze macht und Audienzen gewährt, passt hierher wie der Dom ans Rheinufer. Ludwig II. jetzt in Köln mieten.',
    scene: 'Die Koelnmesse gehört zu den größten Messegeländen der Welt — zur gamescom pilgern Hunderttausende, zur Anuga die globale Food-Branche, zur DMEXCO das digitale Marketing. Wer in diesen Hallen auffallen will, konkurriert mit den lautesten Ständen Europas. Ein König-Roboter gewinnt dieses Duell ohne einen einzigen Dezibel mehr: Menschen bleiben stehen, zücken das Handy, kommen ins Gespräch. Auch abseits der Messe — bei Medienproduktionen, Agentur-Events und Feiern zwischen Rheinauhafen und Ehrenfeld — liefert Ludwig den Moment, der hängen bleibt.',
    venues: [
      { n: 'Koelnmesse', d: 'gamescom, Anuga, DMEXCO, imm cologne — der Roboter macht Ihren Stand zum Pflichttermin der Halle.' },
      { n: 'Congress-Centrum Koelnmesse', d: 'Kongresse und Tagungen mit einem Empfang, den kein Teilnehmer vergisst.' },
      { n: 'Rheinauhafen & Eventlocations', d: 'Produktlaunches und Firmenfeiern mit Rheinblick und royalem Gast.' },
      { n: 'Medien- & TV-Produktionen', d: 'Köln ist Deutschlands TV-Hauptstadt — Ludwig ist kameraerprobt und immer im Charakter.' },
    ],
    faqLoc: 'Koelnmesse und Congress-Centrum, Eventlocations im Rheinauhafen, Hotels, Studios und Stores in der Innenstadt. Ludwig braucht nur eine ebene Fläche, Strom und Internet — alles Weitere planen wir mit Ihnen.',
    nearby: ['bonn', 'duesseldorf', 'aachen', 'wuppertal'],
  },
  {
    slug: 'frankfurt-am-main', name: 'Frankfurt am Main', state: 'Hessen', pop: '780.000',
    intro: 'Buchmesse, Bankenviertel, internationales Publikum: Frankfurt am Main ist Deutschlands Bühne für globale Auftritte. Mieten Sie mit Ludwig II. einen humanoiden Event-Roboter, der auf Messen, Konferenzen und Firmenevents in Frankfurt für königliche Aufmerksamkeit sorgt — auf Deutsch und Englisch.',
    scene: 'Die Messe Frankfurt zählt zu den größten der Welt: Buchmesse, Ambiente, Light + Building, Automechanika. Dazu Kongresse im Kap Europa, Galas in der Festhalle und Corporate Events der Banken- und Beratungswelt. Frankfurts Publikum ist international — und genau dafür ist Ludwig gebaut: Er interagiert live auf Deutsch und Englisch, begrüßt Delegationen und macht aus einem Stand ein Erlebnis. In der Stadt, in der jeder Sekundentakt zählt, stoppt ein König den Lauf der Dinge.',
    venues: [
      { n: 'Messe Frankfurt / Festhalle', d: 'Buchmesse, Ambiente, Light + Building — Ihr Stand wird zur meistbesuchten Adresse der Halle.' },
      { n: 'Kap Europa', d: 'Kongresse und Konferenzen: der Roboter als Eröffnungs-Act oder Networking-Magnet im Foyer.' },
      { n: 'Bankenviertel & Corporate Events', d: 'Empfänge, Jubiläen und Kundenevents mit einem Gast, der jede Dresscode-Debatte gewinnt: Krone schlägt Krawatte.' },
      { n: 'Flughafen & Hotel-Locations', d: 'Internationale Produktlaunches und Tagungen — mehrsprachig, versichert, planbar.' },
    ],
    faqLoc: 'Messe Frankfurt, Kap Europa und Festhalle, Hotels und Eventflächen im Bankenviertel, Showrooms und Locations im gesamten Rhein-Main-Gebiet. Voraussetzungen: ebene Fläche, Strom, Internet — mehr nicht.',
    nearby: ['wiesbaden', 'mannheim', 'bonn'],
  },
  {
    slug: 'stuttgart', name: 'Stuttgart', state: 'Baden-Württemberg', pop: '630.000',
    intro: 'Im Land von Mercedes, Porsche und Bosch weiß man Präzisionstechnik zu schätzen. Ludwig II. bringt sie auf die Eventbühne: ein humanoider Roboter für Messen, Konferenzen und Firmenevents in Stuttgart — schwäbisch gründlich betreut, königlich im Auftritt.',
    scene: 'Die Messe Stuttgart direkt am Flughafen holt mit CMT, R+T und AMB jedes Jahr Hunderttausende in die Region; im ICS tagen Industrie und Mittelstand. Stuttgarts Wirtschaft lebt von Ingenieurskunst — und genau deshalb funktioniert ein humanoider Roboter hier doppelt: als Publikumsmagnet und als Statement, dass Ihr Unternehmen vorne mitspielt. Ob Automotive-Event, Zulieferer-Messe oder Firmenjubiläum in der Region: Ludwig liefert den Auftritt, über den die Halle spricht.',
    venues: [
      { n: 'Messe Stuttgart / ICS', d: 'CMT, AMB, R+T — der König-Roboter zieht Fachbesucher an Ihren Stand, bevor sie beim Wettbewerb landen.' },
      { n: 'Porsche-Arena & Carl Benz Arena', d: 'Firmenevents und Galas im Neckarpark — mit einem Show-Act, der keine Bühne braucht.' },
      { n: 'Automotive- & Industrie-Events', d: 'Wo Technikgeschichte geschrieben wird, gehört ein humanoider Roboter zur Besetzung.' },
      { n: 'Innenstadt & Königstraße', d: 'Store-Eröffnungen und Retail-Aktionen — ein König auf der Königstraße, passender geht es nicht.' },
    ],
    faqLoc: 'Messe Stuttgart und ICS, Porsche-Arena, Carl Benz Arena, Hotels und Eventlocations in der Region — bis zu Showrooms auf der Königstraße. Nötig sind nur ebene Fläche, Strom und Internet.',
    nearby: ['karlsruhe', 'mannheim', 'augsburg', 'muenchen'],
  },
  {
    slug: 'duesseldorf', name: 'Düsseldorf', state: 'Nordrhein-Westfalen', pop: '630.000',
    intro: 'MEDICA, drupa, boot — und die Kö gleich um die Ecke: Düsseldorf verbindet Weltmessen mit Premium-Flair. Ludwig II. passt perfekt dazu: ein humanoider Event-Roboter, den Sie in Düsseldorf für Messen, Konferenzen und exklusive Events mieten können.',
    scene: 'Die Messe Düsseldorf richtet mit MEDICA, drupa, K und interpack einige der wichtigsten Fachmessen der Welt aus; das CCD empfängt Kongresse aller Branchen, das Areal Böhler die Kreativ- und Modewelt. Düsseldorf ist außerdem Deutschlands Werbe- und Modehauptstadt — ein Publikum, das Inszenierung versteht. Ein König-Roboter mit Umhang und Etikette trifft hier genau den Ton: auffällig ohne Effekthascherei, luxuriös ohne Kitsch, und immer bereit für den nächsten viralen Clip.',
    venues: [
      { n: 'Messe Düsseldorf / CCD', d: 'MEDICA, drupa, boot, ProWein — Ludwig macht Ihren Stand zum Gesprächsthema der Weltleitmesse.' },
      { n: 'Areal Böhler', d: 'Fashion-Events, Kreativmessen und Brand-Experiences in Industriekulisse — mit royalem Hauptdarsteller.' },
      { n: 'Königsallee & Retail', d: 'Store-Eröffnungen und Luxus-Aktionen auf der Kö: ein König, der standesgemäß empfängt.' },
      { n: 'Medienhafen', d: 'Agentur-Events, Launches und Firmenfeiern zwischen Gehry-Bauten — Content-Momente garantiert.' },
    ],
    faqLoc: 'Messe Düsseldorf und CCD, Areal Böhler, Locations im Medienhafen, Hotels und Stores auf der Königsallee. Ludwig benötigt nur eine ebene Fläche, Strom und Internet — den Rest stimmen wir gemeinsam ab.',
    nearby: ['koeln', 'duisburg', 'wuppertal', 'moenchengladbach', 'essen'],
  },
  {
    slug: 'leipzig', name: 'Leipzig', state: 'Sachsen', pop: '620.000',
    intro: 'Buchmesse, Boomtown, „Hypezig“: Leipzig ist die dynamischste Stadt Ostdeutschlands — und ein perfektes Pflaster für Auftritte, die geteilt werden. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Konferenzen und Firmenevents in Leipzig.',
    scene: 'Die Leipziger Messe mit ihrer ikonischen Glashalle zieht mit der Buchmesse, OTWorld und zahlreichen Fachkongressen im CCL jährlich ein Millionenpublikum an. Gleichzeitig wachsen in Leipzig Automobilwerke, Logistikzentren und eine lebendige Startup- und Kreativszene zwischen Plagwitz und Baumwollspinnerei. Ein humanoider Roboter trifft hier auf ein Publikum, das Neues feiert statt beäugt — ideal für Markenauftritte, die organische Reichweite suchen.',
    venues: [
      { n: 'Leipziger Messe / CCL', d: 'Buchmesse, OTWorld, Fachkongresse — Ludwig empfängt Ihre Besucher unter der Glashalle.' },
      { n: 'Kongresshalle am Zoo', d: 'Tagungen und Galas im historischen Ambiente — mit einem Gast aus der Zukunft.' },
      { n: 'Baumwollspinnerei & Plagwitz', d: 'Kreativ-Events und Produktlaunches in Industriekulisse — der König im Kontrastprogramm.' },
      { n: 'Automobil- & Logistikstandort', d: 'Werksevents und B2B-Feiern der wachsenden Industrie — Innovation zum Anfassen.' },
    ],
    faqLoc: 'Leipziger Messe und Congress Center Leipzig, Kongresshalle am Zoo, Eventlocations in Plagwitz und der Baumwollspinnerei, Hotels und Stores der Innenstadt. Es genügen ebene Fläche, Strom und Internet.',
    nearby: ['dresden', 'chemnitz', 'berlin', 'hannover'],
  },
  {
    slug: 'dortmund', name: 'Dortmund', state: 'Nordrhein-Westfalen', pop: '600.000',
    intro: 'Vom Stahlstandort zur Tech- und Eventstadt: Dortmund füllt Hallen — ob Westfalenhallen, Stadion oder Kongresszentrum. Mit Ludwig II. mieten Sie einen humanoiden Event-Roboter, der auf Messen und Firmenevents in Dortmund für Momente sorgt, die das Ruhrgebiet teilt.',
    scene: 'Die Westfalenhallen gehören zu den traditionsreichsten Veranstaltungsorten Deutschlands: Messen wie die Jagd & Hund — Europas größte ihrer Art — und die InterTabac holen internationales Publikum in die Stadt, das angeschlossene Kongresszentrum füllt den Kalender mit Tagungen. Gleichzeitig wächst am Phoenix-See und im Technologiepark eine selbstbewusste IT- und Logistikszene. Ein König-Roboter passt zu diesem Aufbruch: ehrliche Begeisterung statt Buzzword-Bingo — und ein Fotomotiv, das jede Halle erobert.',
    venues: [
      { n: 'Messe Dortmund / Westfalenhallen', d: 'Jagd & Hund, InterTabac & Co. — Ludwig macht Ihren Stand zur Attraktion der Halle.' },
      { n: 'Kongresszentrum Westfalenhallen', d: 'Tagungen und Kongresse mit einem Empfang, der in Erinnerung bleibt.' },
      { n: 'Phoenix-See & Technologiepark', d: 'Firmenevents der Tech- und Logistikszene — Zukunft zum Anfassen am Seeufer.' },
      { n: 'Signal Iduna Park (Business-Events)', d: 'Kundenevents und Feiern im größten Stadion Deutschlands — königlicher Auftritt vor großer Kulisse.' },
    ],
    faqLoc: 'Westfalenhallen und Kongresszentrum, Eventlocations am Phoenix-See, Business-Bereiche im Signal Iduna Park, Hotels und Firmengelände in der Region. Nötig: ebene Fläche, Strom, Internet.',
    nearby: ['bochum', 'essen', 'gelsenkirchen', 'muenster'],
  },
  {
    slug: 'essen', name: 'Essen', state: 'Nordrhein-Westfalen', pop: '580.000',
    intro: 'SPIEL, E-world, Zollverein: Essen verbindet Messegeschäft mit Weltkulturerbe. Ein humanoider Event-Roboter, der zwischen Industriedenkmal und Messehalle Hof hält — das ist ein Kontrast, der Bilder produziert. Ludwig II. jetzt in Essen mieten.',
    scene: 'Die Messe Essen ist Heimat der SPIEL — der größten Brettspielmesse der Welt — sowie der E-world energy & water und der Techno-Classica. Dazu kommen Kongresse in der Grugahalle und Events auf dem UNESCO-Welterbe Zollverein, einer der spektakulärsten Kulissen Deutschlands. Essen sitzt im Herzen der Energiewirtschaft und des Ruhrgebiets-Mittelstands: ein Publikum, das Substanz erwartet. Ludwig liefert beides — echte Robotik zum Anfassen und einen Auftritt mit Unterhaltungswert.',
    venues: [
      { n: 'Messe Essen', d: 'SPIEL, E-world, Techno-Classica — der König-Roboter zieht die Besucherströme an Ihren Stand.' },
      { n: 'Grugahalle', d: 'Kongresse, Shows und Firmenveranstaltungen — mit einem Highlight, das kein Programmheft braucht.' },
      { n: 'UNESCO-Welterbe Zollverein', d: 'Galas und Brand-Events vor Industriekulisse: Krone trifft Koks-Ofen — unbezahlbare Fotomotive.' },
      { n: 'Energie- & Konzernevents', d: 'Kundenveranstaltungen der Energiebranche — Innovation als Erlebnis statt als Folie 37.' },
    ],
    faqLoc: 'Messe Essen, Grugahalle, Eventflächen auf Zollverein, Hotels und Konzernstandorte im Ruhrgebiet. Ludwig braucht nur eine ebene Fläche, Strom und Internet — auch in historischer Industriekulisse.',
    nearby: ['duisburg', 'bochum', 'gelsenkirchen', 'duesseldorf'],
  },
  {
    slug: 'bremen', name: 'Bremen', state: 'Bremen', pop: '570.000',
    intro: 'Raumfahrt, Windkraft, Häfen: Bremen baut an der Zukunft — da darf ein humanoider Roboter auf Events nicht fehlen. Mieten Sie Ludwig II. für Messen, Konferenzen und Firmenevents in Bremen: königlicher Auftritt, hanseatisch zuverlässig organisiert.',
    scene: 'In Bremen entstehen Satelliten, Flugzeugflügel und Offshore-Windparks — Airbus, OHB und die Häfen prägen eine Wirtschaft, die Hightech gewohnt ist. Auf der Messe Bremen und in der ÖVB-Arena treffen sich Publikums- und Fachmessen, im Congress Centrum tagen Verbände und Unternehmen, und die Überseestadt liefert moderne Eventflächen am Wasser. Ein König-Roboter macht daraus einen Anlass: Er begrüßt, unterhält, posiert — und Ihr Unternehmen liefert das Gesprächsthema der Hansestadt.',
    venues: [
      { n: 'Messe Bremen & ÖVB-Arena', d: 'Publikums- und Fachmessen — Ludwig verwandelt Ihren Stand in die Hauptattraktion.' },
      { n: 'Congress Centrum Bremen', d: 'Tagungen und Kongresse mit einem Empfang, der hanseatische Zurückhaltung charmant bricht.' },
      { n: 'Überseestadt & BLG-Forum', d: 'Firmenevents und Launches am Wasser — moderne Kulisse für einen royalen Gast.' },
      { n: 'Luft- & Raumfahrt-Events', d: 'Wo Satelliten gebaut werden, ist ein humanoider Roboter der passende Ehrengast.' },
    ],
    faqLoc: 'Messe Bremen, ÖVB-Arena, Congress Centrum, Locations in der Überseestadt sowie Hotels und Firmenstandorte der Region. Voraussetzungen: ebene Fläche, Strom und Internetzugang.',
    nearby: ['hamburg', 'hannover', 'kiel'],
  },
  {
    slug: 'dresden', name: 'Dresden', state: 'Sachsen', pop: '560.000',
    intro: 'Barockstadt trifft „Silicon Saxony“: In Dresden liegen Zwinger und Chipfabrik nur Minuten auseinander. Ein humanoider Roboter mit Krone fügt sich da erstaunlich organisch ein. Mieten Sie Ludwig II. für Messen, Kongresse und Firmenevents in Dresden.',
    scene: 'Dresden ist Europas größter Mikroelektronik-Standort — Infineon, Bosch und bald ESMC fertigen hier die Chips, ohne die kein Roboter läuft. Entsprechend technikaffin ist das Publikum auf Kongressen im Internationalen Congress Center, auf Messen in der Messe Dresden und bei Firmenevents zwischen Altstadt und Elbufer. Ludwig II. schlägt hier die Brücke, die keine Marketingfolie schafft: von der sächsischen Residenzgeschichte zur Halbleiter-Zukunft — mit Krone, Umhang und perfektem Timing.',
    venues: [
      { n: 'Messe Dresden', d: 'Fach- und Publikumsmessen — der König-Roboter macht Ihren Stand zum Besuchermagneten.' },
      { n: 'Internationales Congress Center', d: 'Kongresse mit Elbblick: Ludwig als Eröffnungsmoment oder Pausen-Attraktion.' },
      { n: 'Halbleiter- & Tech-Events', d: 'Im Herzen von Silicon Saxony ist ein humanoider Roboter der glaubwürdigste Botschafter.' },
      { n: 'Altstadt & Premium-Locations', d: 'Galas und Feiern zwischen Frauenkirche und Zwinger — royaler Auftritt in royaler Kulisse.' },
    ],
    faqLoc: 'Messe Dresden, Internationales Congress Center, Hotels und historische Locations der Altstadt sowie Tech-Campus-Events in Silicon Saxony. Es genügen ebene Fläche, Strom und Internet.',
    nearby: ['leipzig', 'chemnitz', 'berlin'],
  },
  {
    slug: 'hannover', name: 'Hannover', state: 'Niedersachsen', pop: '550.000',
    intro: 'Heimat der HANNOVER MESSE — der Weltleitmesse der Industrie: Nirgendwo ist ein humanoider Roboter näher an seinem Publikum als in Hannover. Mieten Sie Ludwig II. für Messen, Kongresse und Firmenevents auf dem größten Messegelände der Welt und in der ganzen Region.',
    scene: 'Hannover besitzt das größte Messegelände der Welt: HANNOVER MESSE, Agritechnica, EMO, DOMOTEX und IdeenExpo holen jedes Jahr Aussteller und Besucher aus über 100 Ländern. Wenn irgendwo über Robotik, Automation und Industrie 4.0 gesprochen wird, dann hier — und ein humanoider Roboter am Stand ist der Unterschied zwischen „davon reden“ und „es zeigen“. Dazu kommen Kongresse im HCC und Firmenevents einer Region, in der Volkswagen Nutzfahrzeuge, Continental und ein starker Mittelstand zu Hause sind.',
    venues: [
      { n: 'Messegelände Hannover', d: 'HANNOVER MESSE, EMO, Agritechnica — Ludwig zeigt live, was Ihre Folien nur behaupten.' },
      { n: 'Hannover Congress Centrum (HCC)', d: 'Kongresse und Tagungen im Stadthallen-Ambiente — mit königlichem Empfang.' },
      { n: 'IdeenExpo & Tech-Formate', d: 'Europas größtes Jugend-Technikevent: Begeisterung für Robotik, die ansteckt.' },
      { n: 'Industrie- & Firmenevents', d: 'Werksjubiläen, Kundentage, Produktlaunches — Innovation, die Hände schüttelt.' },
    ],
    faqLoc: 'Messegelände Hannover, HCC, ZAG-Arena, Hotels und Firmenstandorte der Region. Ludwig braucht nur eine ebene Fläche, Strom und Internet — auf dem größten Messegelände der Welt findet sich die immer.',
    nearby: ['braunschweig', 'bielefeld', 'hamburg', 'bremen'],
  },
  {
    slug: 'nuernberg', name: 'Nürnberg', state: 'Bayern', pop: '520.000',
    intro: 'Spielwarenmesse, embedded world, Christkindlesmarkt: Nürnberg kann Weltmessen und Wow-Momente. Ein humanoider Event-Roboter, der Besucher begrüßt und Audienzen hält, gehört genau hierher. Ludwig II. jetzt für Events in Nürnberg mieten.',
    scene: 'Die NürnbergMesse zählt zu den 15 größten Messegesellschaften der Welt: Auf der Spielwarenmesse wird die Zukunft des Spielens verhandelt, auf der embedded world die Zukunft der Elektronik — Ludwigs Innenleben inklusive. Dazu kommen BIOFACH, BrauBeviale und ein dichter Kongresskalender im NCC. Nürnbergs Mischung aus Tradition (Burg, Altstadt, Handwerk) und Hightech (Halbleiter, Automation) ist der perfekte Rahmen für einen König aus Karbon und Code.',
    venues: [
      { n: 'NürnbergMesse / NCC', d: 'Spielwarenmesse, embedded world, BIOFACH — Ludwig macht Ihren Stand zum meistfotografierten Ort der Halle.' },
      { n: 'Meistersingerhalle', d: 'Kongresse, Galas und Festakte — mit einem Ehrengast, der garantiert pünktlich ist.' },
      { n: 'Altstadt & Burgkulisse', d: 'Brand-Events und Drehs zwischen Fachwerk und Kaiserburg — König trifft Kaiserstadt.' },
      { n: 'Tech- & Industrie-Events', d: 'Elektronik- und Automatisierungsbranche: Ihr Produkt, präsentiert von einem Roboter.' },
    ],
    faqLoc: 'NürnbergMesse und NCC, Meistersingerhalle, Arena Nürnberger Versicherung, Hotels und Eventlocations der Altstadt. Voraussetzungen sind nur ebene Fläche, Strom und Internet.',
    nearby: ['muenchen', 'augsburg', 'chemnitz'],
  },
  {
    slug: 'duisburg', name: 'Duisburg', state: 'Nordrhein-Westfalen', pop: '500.000',
    intro: 'Größter Binnenhafen der Welt, Stahl, Logistik — und mit dem Landschaftspark eine der spektakulärsten Eventkulissen Europas: Duisburg hat Bühnen, die es nur hier gibt. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Ihren Auftritt in Duisburg.',
    scene: 'Duisburg verbindet Industriegeschichte mit Logistik-Zukunft: duisport bewegt Güter aus aller Welt, thyssenkrupp prägt die Stahlkultur, und im Landschaftspark Duisburg-Nord feiern Unternehmen zwischen Hochöfen unter Flutlicht. Die Mercatorhalle im CityPalais füllt den Kongresskalender, der Innenhafen liefert moderne Eventflächen am Wasser. Ein König-Roboter vor Hochofenkulisse — das ist der Kontrast, aus dem virale Bilder gemacht sind.',
    venues: [
      { n: 'Mercatorhalle / CityPalais', d: 'Kongresse und Tagungen im Herzen der Stadt — mit royalem Empfangskomitee.' },
      { n: 'Landschaftspark Duisburg-Nord', d: 'Galas und Brand-Events zwischen Hochöfen — die dramatischste Kulisse des Ruhrgebiets.' },
      { n: 'Innenhafen', d: 'Firmenevents und Launches am Wasser — Industriecharme trifft königliche Etikette.' },
      { n: 'Logistik- & Industrie-Events', d: 'Kundentage und Jubiläen von Hafen bis Stahlwerk — Zukunftstechnik zum Anfassen.' },
    ],
    faqLoc: 'Mercatorhalle und CityPalais, Landschaftspark Duisburg-Nord, Locations am Innenhafen sowie Firmengelände in Hafen- und Industrienähe. Nötig sind ebene Fläche, Strom und Internet.',
    nearby: ['essen', 'duesseldorf', 'moenchengladbach', 'gelsenkirchen'],
  },
  {
    slug: 'bochum', name: 'Bochum', state: 'Nordrhein-Westfalen', pop: '365.000',
    intro: 'Jahrhunderthalle, RuhrCongress, IT-Security-Hochburg: Bochum hat sich vom Bergbau zur Wissensstadt gewandelt — und feiert das in Kulissen, die ihresgleichen suchen. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Events und Kongresse in Bochum.',
    scene: 'In Bochum tagt die IT-Sicherheitsbranche (G DATA und das Bochumer Security-Cluster sind hier zu Hause), im RuhrCongress treffen sich Verbände und Unternehmen, und die Jahrhunderthalle gilt als eine der eindrucksvollsten Industrie-Eventlocations Europas. Ein humanoider Roboter, der durch eine Halle aus dem Jahr 1902 schreitet, erzählt die Geschichte des Strukturwandels besser als jede Broschüre — und Ihr Event liefert die Bilder dazu.',
    venues: [
      { n: 'RuhrCongress Bochum', d: 'Kongresse und Tagungen — Ludwig empfängt Ihre Gäste und eröffnet mit königlicher Geste.' },
      { n: 'Jahrhunderthalle', d: 'Galas und Brand-Events in historischer Industriearchitektur — Gänsehaut-Kulisse inklusive.' },
      { n: 'IT- & Security-Events', d: 'Wo über Cybersicherheit gesprochen wird, ist ein KI-Roboter das perfekte Anschauungsobjekt.' },
      { n: 'Hochschul- & Wissenschaftsformate', d: 'Ruhr-Universität und Hochschulen: Robotik zum Anfassen für den Nachwuchs.' },
    ],
    faqLoc: 'RuhrCongress, Jahrhunderthalle, Vonovia Ruhrstadion (Business-Events), Hochschul-Campus und Hotels der Region. Es genügen ebene Fläche, Strom und Internet.',
    nearby: ['dortmund', 'essen', 'gelsenkirchen', 'wuppertal'],
  },
  {
    slug: 'wuppertal', name: 'Wuppertal', state: 'Nordrhein-Westfalen', pop: '360.000',
    intro: 'Die Stadt der Schwebebahn weiß, wie man Technik zur Attraktion macht — seit 1901. Ludwig II. setzt die Tradition fort: ein humanoider Event-Roboter für Messen, Tagungen und Firmenevents in Wuppertal, majestätisch im Auftritt, präzise im Betrieb.',
    scene: 'Wuppertals Historische Stadthalle zählt zu den schönsten Veranstaltungshäusern Europas — Kongresse und Galas bekommen hier automatisch Weltniveau. Dazu kommt ein Mittelstand mit Weltruf: Vorwerk, Knipex und die Bayer-Historie stehen für Erfindergeist aus dem Bergischen Land. Ein König-Roboter zwischen Jugendstil-Säulen oder auf dem Werksgelände eines Hidden Champions — das sind Auftritte, die Belegschaft, Kunden und lokale Presse gleichermaßen begeistern.',
    venues: [
      { n: 'Historische Stadthalle', d: 'Kongresse und Festakte in einem der prächtigsten Säle Europas — royaler geht Kulisse nicht.' },
      { n: 'Unternehmens- & Werksevents', d: 'Jubiläen und Kundentage des Bergischen Mittelstands — Innovation trifft Tradition.' },
      { n: 'Utopiastadt & Kreativorte', d: 'Launches und Community-Events im Mirker Bahnhof — der König im Aufbruchsquartier.' },
      { n: 'Messen & Regionalformate', d: 'Regionale Fach- und Verbraucherformate — Ludwig macht Ihren Auftritt zum Stadtgespräch.' },
    ],
    faqLoc: 'Historische Stadthalle, Hotels, Werksgelände und Kreativlocations wie Utopiastadt. Ludwig braucht eine ebene Fläche, Strom und Internet — die Schwebebahn nimmt er allerdings nicht.',
    nearby: ['duesseldorf', 'koeln', 'essen', 'bochum'],
  },
  {
    slug: 'bielefeld', name: 'Bielefeld', state: 'Nordrhein-Westfalen', pop: '340.000',
    intro: 'Es gibt Bielefeld wirklich — und mit Ludwig II. gibt es dort jetzt auch einen König: Mieten Sie den humanoiden Event-Roboter für Messen, Kongresse und Firmenevents in Bielefeld und Ostwestfalen-Lippe. Ein Beweisfoto liefert er gleich mit.',
    scene: 'Ostwestfalen-Lippe ist eine der stärksten Mittelstandsregionen Europas: Dr. Oetker, Schüco, Seidensticker und Hunderte Hidden Champions haben hier ihren Sitz — und die Universität Bielefeld forscht seit Jahren international sichtbar an Robotik und interaktiver KI. In der Stadthalle Bielefeld tagen Wirtschaft und Verbände, im Lokschuppen feiern Unternehmen in Industriekulisse. Ein humanoider Roboter trifft hier auf ein Publikum, das Technik nicht bestaunt, sondern einordnet — und genau deshalb umso mehr Respekt vor einem gelungenen Live-Auftritt hat.',
    venues: [
      { n: 'Stadthalle Bielefeld', d: 'Kongresse und Tagungen im Zentrum — Ludwig begrüßt, eröffnet und bleibt im Gedächtnis.' },
      { n: 'Lokschuppen Bielefeld', d: 'Firmenfeiern und Galas in Industriearchitektur — mit königlichem Überraschungsgast.' },
      { n: 'Mittelstands- & Werksevents', d: 'Jubiläen und Kundentage der OWL-Champions — Zukunft zum Anfassen statt Folienschlacht.' },
      { n: 'Hochschul- & Forschungsformate', d: 'Robotik-Uni trifft Robotik-König: Wissenschaftsevents mit Publikumsmagnet.' },
    ],
    faqLoc: 'Stadthalle Bielefeld, Lokschuppen, Rudolf-Oetker-Halle, Hochschul-Campus sowie Werksgelände in ganz OWL. Voraussetzungen: ebene Fläche, Strom, Internet.',
    nearby: ['muenster', 'hannover', 'dortmund'],
  },
  {
    slug: 'bonn', name: 'Bonn', state: 'Nordrhein-Westfalen', pop: '340.000',
    intro: 'UN-Stadt, DAX-Standort, Beethovens Geburtsort: Bonn empfängt die Welt — und jetzt auch einen König. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Kongresse, Konferenzen und Firmenevents in Bonn: diplomatisch auf Deutsch und Englisch.',
    scene: 'Im World Conference Center Bonn tagen UN-Konferenzen und internationale Kongresse, Deutsche Telekom und Deutsche Post DHL steuern von hier globale Geschäfte, und dazwischen feiert eine Stadt, die Repräsentation seit Bundeshauptstadt-Zeiten beherrscht. Ludwig II. passt in dieses Umfeld wie kein zweiter Act: mehrsprachig, protokollsicher, mit einem Auftreten irgendwo zwischen Staatsgast und Show-Star — und immer für ein diplomatisches Bonmot zu haben.',
    venues: [
      { n: 'World Conference Center Bonn', d: 'Internationale Kongresse und Konferenzen — Ludwig empfängt Delegationen auf Deutsch und Englisch.' },
      { n: 'DAX- & Konzernevents', d: 'Telekom, DHL & Co.: Kundenevents und Townhalls mit einem Gast, über den alle sprechen.' },
      { n: 'Kameha Grand & Rheinufer', d: 'Galas und Premium-Feiern am Rhein — königliche Präsenz in Fünf-Sterne-Kulisse.' },
      { n: 'Bundeskunsthalle & Museumsmeile', d: 'Kultur- und Presse-Events — ein Roboter, der selbst zum Ausstellungsstück taugt.' },
    ],
    faqLoc: 'WCCB, Hotels wie das Kameha Grand, Konzernstandorte, Bundeskunsthalle und Locations am Rheinufer. Ludwig benötigt nur ebene Fläche, Strom und Internet.',
    nearby: ['koeln', 'duesseldorf', 'aachen'],
  },
  {
    slug: 'muenster', name: 'Münster', state: 'Nordrhein-Westfalen', pop: '320.000',
    intro: 'Friedensstadt, Fahrradhauptstadt, Versicherungsstandort: Münster verbindet historische Kulisse mit junger Uni-Energie. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Kongresse und Firmenevents in Münster — ein Auftritt, der Geschichte schreibt.',
    scene: 'Im MCC Halle Münsterland treffen sich Messen und Kongresse des Münsterlands, LVM und Provinzial prägen einen starken Versicherungs- und Dienstleistungsstandort, und fast 65.000 Studierende halten die Stadt jung. Wo 1648 der Westfälische Friede verhandelt wurde, verhandelt Ludwig heute Selfie-Anfragen: Ein König-Roboter zwischen Prinzipalmarkt und modernem Kongresszentrum liefert genau die Mischung aus Witz und Würde, die Münster liebt.',
    venues: [
      { n: 'MCC Halle Münsterland', d: 'Messen und Kongresse des Münsterlands — Ludwig macht Ihren Stand zum Publikumsliebling.' },
      { n: 'Historisches Rathaus & Prinzipalmarkt', d: 'Empfänge und Festakte in Friedenssaal-Nähe — royale Präsenz in historischen Mauern.' },
      { n: 'Versicherungs- & Dienstleisterevents', d: 'Kundentage und Jubiläen von LVM bis Provinzial — Digitalisierung, die Hände schüttelt.' },
      { n: 'Hafen & Kreativkai', d: 'Firmenfeiern und Launches am Stadthafen — junger Standort, königlicher Gast.' },
    ],
    faqLoc: 'MCC Halle Münsterland, Hotels, historische Säle der Altstadt und Locations am Kreativkai. Es genügen eine ebene Fläche, Strom und Internetzugang.',
    nearby: ['dortmund', 'bielefeld', 'gelsenkirchen'],
  },
  {
    slug: 'mannheim', name: 'Mannheim', state: 'Baden-Württemberg', pop: '320.000',
    intro: 'Quadratestadt, Erfinderstadt, Heimat der größten Regionalmesse Deutschlands: Mannheim denkt praktisch — und feiert groß. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Kongresse und Firmenevents in Mannheim und der Rhein-Neckar-Region.',
    scene: 'Vom Maimarkt — Deutschlands größter Regionalmesse — über Kongresse im Rosengarten bis zu Konzern-Events von ABB, Roche und John Deere: Die Rhein-Neckar-Region bündelt Industrie, Forschung und Eventkultur auf engstem Raum. Mannheim hat das Auto und das Fahrrad miterfunden; ein humanoider Roboter als nächstes Kapitel der Technikgeschichte trifft hier auf ein Publikum, das Erfindungen zu würdigen weiß — am liebsten live und zum Anfassen.',
    venues: [
      { n: 'Congress Center Rosengarten', d: 'Kongresse und Tagungen im Herzen der Quadrate — mit königlichem Empfang.' },
      { n: 'Maimarkt Mannheim', d: 'Deutschlands größte Regionalmesse — Ludwig macht Ihren Stand zum Tagesgespräch.' },
      { n: 'SAP Arena (Business-Events)', d: 'Kundenevents und Feiern im großen Rahmen — der König füllt jede Bühne.' },
      { n: 'Industrie- & Konzernevents', d: 'ABB, Roche, John Deere & Mittelstand: Innovation, die auf Ihrem Event Hände schüttelt.' },
    ],
    faqLoc: 'Rosengarten, Maimarktgelände, SAP Arena (Business-Bereiche), Hotels und Werksgelände in der Rhein-Neckar-Region. Nötig sind ebene Fläche, Strom und Internet.',
    nearby: ['frankfurt-am-main', 'karlsruhe', 'stuttgart', 'wiesbaden'],
  },
  {
    slug: 'karlsruhe', name: 'Karlsruhe', state: 'Baden-Württemberg', pop: '310.000',
    intro: 'Fächerstadt, IT-Hochburg, Residenz des Rechts: Karlsruhe wurde von einem Markgrafen am Reißbrett entworfen — royale Planung liegt der Stadt also im Blut. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Kongresse und Events in Karlsruhe.',
    scene: 'Mit dem KIT, dem CyberForum und einer der höchsten IT-Dichten Europas ist Karlsruhe deutsche Digital-Hauptstadt im Südwesten; auf der Messe Karlsruhe treffen sich art KARLSRUHE und die LEARNTEC — Europas Leitmesse für digitale Bildung. Dazu kommen Kongresse in der Stadthalle und Medienkunst im ZKM. Ein humanoider Roboter ist hier kein Gimmick, sondern Fachgespräch auf zwei Beinen: Ludwig zieht das Publikum an, Ihr Team führt die Gespräche.',
    venues: [
      { n: 'Messe Karlsruhe', d: 'LEARNTEC, art KARLSRUHE & Fachmessen — der König-Roboter macht Ihren Stand unübersehbar.' },
      { n: 'Stadthalle / Kongresszentrum', d: 'Kongresse und Tagungen im Zentrum der Fächerstadt — mit royalem Auftakt.' },
      { n: 'ZKM & Kreativ-Events', d: 'Medienkunst trifft Robotik — Formate an der Schnittstelle von Kultur und Technologie.' },
      { n: 'IT- & Startup-Events', d: 'KIT, CyberForum, Tech-Konferenzen: Robotik zum Anfassen für ein Publikum, das den Code dahinter versteht.' },
    ],
    faqLoc: 'Messe Karlsruhe, Stadthalle, ZKM, Hochschul-Campus und Hotels der Region. Ludwig braucht nur eine ebene Fläche, Strom und Internet.',
    nearby: ['mannheim', 'stuttgart', 'frankfurt-am-main'],
  },
  {
    slug: 'augsburg', name: 'Augsburg', state: 'Bayern', pop: '300.000',
    intro: 'Fuggerstadt und deutsche Robotik-Hauptstadt: In Augsburg hat KUKA seinen Sitz — Roboter gehören hier zur Stadtgeschichte. Zeit, dass einer König wird: Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Kongresse und Firmenevents in Augsburg.',
    scene: 'Kaum eine deutsche Stadt hat eine engere Beziehung zur Robotik als Augsburg: KUKA baut hier seit Jahrzehnten Industrieroboter für die ganze Welt, Hochschule und DLR forschen an der Produktion von morgen. Auf der Messe Augsburg und im Kongress am Park treffen sich Fachwelt und Mittelstand, im Goldenen Saal des Rathauses empfängt die Stadt seit der Fugger-Zeit ihre Gäste. Ein humanoider König-Roboter schließt hier einen historischen Kreis — vom Handelsimperium zur Automation, mit Augenzwinkern.',
    venues: [
      { n: 'Messe Augsburg', d: 'Fachmessen wie interlift & Co. — Ludwig zieht das Fachpublikum an Ihren Stand.' },
      { n: 'Kongress am Park', d: 'Kongresse und Tagungen im denkmalgeschützten Ambiente — mit royalem Empfang.' },
      { n: 'Robotik- & Industrie-Events', d: 'In der Stadt von KUKA ist ein humanoider Roboter der glaubwürdigste Gastredner.' },
      { n: 'Rathaus & historische Säle', d: 'Festakte und Empfänge zwischen Fuggerei und Goldenem Saal — Geschichte trifft Zukunft.' },
    ],
    faqLoc: 'Messe Augsburg, Kongress am Park, historische Säle der Altstadt, Hochschul-Campus und Firmengelände der Region. Voraussetzungen: ebene Fläche, Strom, Internet.',
    nearby: ['muenchen', 'nuernberg', 'stuttgart'],
  },
  {
    slug: 'wiesbaden', name: 'Wiesbaden', state: 'Hessen', pop: '280.000',
    intro: 'Kurstadt, Landeshauptstadt, Versicherungsstandort: Wiesbaden empfängt seit Kaiserzeiten anspruchsvolle Gäste — Ludwig II. fühlt sich hier standesgemäß wohl. Mieten Sie den humanoiden Event-Roboter für Kongresse, Tagungen und Premium-Events in Wiesbaden.',
    scene: 'Das RheinMain CongressCenter zählt zu den modernsten Kongresshäusern Europas, das Kurhaus mit seinem legendären Festsaal zu den prächtigsten — zwischen beiden liegt Wiesbadens Anspruch: Veranstaltungen mit Niveau. R+V und die Versicherungsbranche, Landespolitik und ein wohlhabendes Einzugsgebiet sorgen für einen dichten Kalender an Tagungen, Galas und Kundenevents. Ein König-Roboter im Kurhaus-Foyer — würdevoller lässt sich Zukunft nicht inszenieren.',
    venues: [
      { n: 'RheinMain CongressCenter', d: 'Kongresse und Tagungen auf Top-Niveau — Ludwig eröffnet, begrüßt und begeistert.' },
      { n: 'Kurhaus Wiesbaden', d: 'Galas und Festakte im Festsaal — royale Präsenz in kaiserzeitlicher Pracht.' },
      { n: 'Versicherungs- & Finanzevents', d: 'Kundentage und Jubiläen der Branche — Digitalisierung als Erlebnis statt Schlagwort.' },
      { n: 'Premium-Feiern im Rheingau', d: 'Exklusive Feiern zwischen Weinbergen und Villen — der König reist selbstverständlich an.' },
    ],
    faqLoc: 'RheinMain CongressCenter, Kurhaus, Hotels und Locations in Stadt und Rheingau. Ludwig benötigt lediglich ebene Fläche, Strom und Internet.',
    nearby: ['frankfurt-am-main', 'mannheim', 'bonn'],
  },
  {
    slug: 'moenchengladbach', name: 'Mönchengladbach', state: 'Nordrhein-Westfalen', pop: '270.000',
    intro: 'Textiltradition, Borussia, Aufbruchsgeist: Mönchengladbach erfindet sich neu — und feiert das gern in großem Rahmen. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Firmenevents und Feiern in Mönchengladbach und am Niederrhein.',
    scene: 'Der BORUSSIA-PARK ist längst mehr als ein Stadion: Business-Events, Tagungen und Feiern füllen seine Logen und Hallen das ganze Jahr. Dazu kommen die Kaiser-Friedrich-Halle für Festakte, eine wachsende Digital- und Logistikszene und die Textilgeschichte, die mit Hochschule Niederrhein und Textilakademie in die Zukunft verlängert wird. Ein König-Roboter am Niederrhein — das ist der Auftritt, mit dem Ihr Event die Region überrascht.',
    venues: [
      { n: 'BORUSSIA-PARK (Business-Events)', d: 'Kundenevents und Feiern im Stadion — Ludwig spielt in jeder Liga.' },
      { n: 'Kaiser-Friedrich-Halle', d: 'Festakte und Galas im Jugendstil-Juwel — royale Kulisse für einen royalen Gast.' },
      { n: 'Textil- & Wirtschaftsevents', d: 'Vom Mittelstand bis zur Hochschule Niederrhein: Innovation, die man anfassen kann.' },
      { n: 'Nordpark & moderne Locations', d: 'Launches und Firmenfeiern im Businesspark — Zukunftstechnik als Hauptattraktion.' },
    ],
    faqLoc: 'BORUSSIA-PARK, Kaiser-Friedrich-Halle, Locations im Nordpark sowie Hotels und Werksgelände am Niederrhein. Es genügen ebene Fläche, Strom und Internet.',
    nearby: ['duesseldorf', 'duisburg', 'koeln', 'aachen'],
  },
  {
    slug: 'gelsenkirchen', name: 'Gelsenkirchen', state: 'Nordrhein-Westfalen', pop: '260.000',
    intro: 'Von der Kohle zur Solarstadt, vom Fußballtempel zum Eventstandort: Gelsenkirchen kann große Bühnen. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Firmenevents, Messen und Feiern in Gelsenkirchen — ein Auftritt, der auf Schalke und darüber hinaus Gesprächsthema wird.',
    scene: 'Die VELTINS-Arena gehört zu den vielseitigsten Veranstaltungsorten Europas — vom Konzert bis zum Firmenevent in den Business-Bereichen. Der Wissenschaftspark steht für den Wandel zur Zukunftsenergie, der Nordsternpark liefert Industrie-Romantik am Kanal, und das Musiktheater im Revier zählt zu den schönsten Theaterbauten der Nachkriegszeit. Ein König-Roboter in dieser Kulisse erzählt die Geschichte, die Gelsenkirchen gerade schreibt: Wandel, den man erleben kann.',
    venues: [
      { n: 'VELTINS-Arena (Business-Events)', d: 'Kundenevents und Feiern in Arena-Dimension — Ludwig füllt auch diese Bühne.' },
      { n: 'Wissenschaftspark', d: 'Tagungen und Innovationsformate im Solarstadt-Wahrzeichen — Zukunft trifft Zukunft.' },
      { n: 'Nordsternpark', d: 'Firmenfeiern und Events am Kanal — Industriekulisse mit königlichem Kontrast.' },
      { n: 'Musiktheater im Revier', d: 'Galas und Festakte in Architektur-Ikone — großer Auftritt garantiert.' },
    ],
    faqLoc: 'VELTINS-Arena (Business-Bereiche), Wissenschaftspark, Nordsternpark und Hotels der Region. Ludwig braucht eine ebene Fläche, Strom und Internet — mehr nicht.',
    nearby: ['essen', 'bochum', 'dortmund', 'duisburg'],
  },
  {
    slug: 'aachen', name: 'Aachen', state: 'Nordrhein-Westfalen', pop: '250.000',
    intro: 'Kaiserstadt Karls des Großen und Europas Ingenieurschmiede: In Aachen wurden Könige gekrönt — Ludwig II. fühlt sich also historisch bestens aufgehoben. Mieten Sie den humanoiden Event-Roboter für Kongresse, Messen und Firmenevents in Aachen.',
    scene: 'Die RWTH Aachen gehört zu den besten Technik-Universitäten Europas und forscht selbst an Robotik und KI — Ludwigs Auftritt trifft hier auf ein Publikum, das jede Bewegung fachkundig würdigt. Im Eurogress tagen internationale Kongresse, beim CHIO trifft sich der Weltsport, und im Krönungssaal des Rathauses wird jährlich der Karlspreis verliehen. Eine Stadt, die seit 1.200 Jahren Herrscher empfängt, bekommt mit Ludwig endlich wieder royalen Besuch — diesmal aus Karbon.',
    venues: [
      { n: 'Eurogress Aachen', d: 'Internationale Kongresse und Tagungen — Ludwig empfängt auf Deutsch und Englisch.' },
      { n: 'RWTH & Forschungs-Events', d: 'Robotik-Kongresse, Institutsjubiläen, Recruiting-Events — der König als Fachgespräch auf zwei Beinen.' },
      { n: 'CHIO & Großevents', d: 'Sponsoren- und VIP-Bereiche der Großevents — ein Auftritt, der auch neben Weltsport besteht.' },
      { n: 'Historisches Rathaus & Altstadt', d: 'Empfänge und Festakte in der Krönungsstadt — Geschichte trifft Zukunftstechnik.' },
    ],
    faqLoc: 'Eurogress, RWTH-Campus und Cluster Smart Logistik, Business-Bereiche der Großevents, historische Säle und Hotels. Voraussetzungen: ebene Fläche, Strom, Internet.',
    nearby: ['koeln', 'bonn', 'moenchengladbach', 'duesseldorf'],
  },
  {
    slug: 'braunschweig', name: 'Braunschweig', state: 'Niedersachsen', pop: '250.000',
    intro: 'Löwenstadt und Europas forschungsintensivste Region: In Braunschweig arbeiten mehr Wissenschaftler pro Kopf als fast überall sonst auf dem Kontinent. Das perfekte Publikum für einen humanoiden Roboter — mieten Sie Ludwig II. für Events, Messen und Kongresse in Braunschweig.',
    scene: 'DLR, PTB, TU Braunschweig und die Nähe zu Volkswagen machen die Region zwischen Braunschweig und Wolfsburg zu einem der dichtesten Forschungsstandorte Europas — autonome Systeme und Mobilität von morgen entstehen genau hier. In der Stadthalle und der Volkswagen Halle treffen sich Kongresse, Shows und Firmenevents. Heinrich der Löwe machte Braunschweig einst zur Residenz; Ludwig II. knüpft daran an — als erster König der Stadt, der über eine eigene Firmware verfügt.',
    venues: [
      { n: 'Stadthalle Braunschweig', d: 'Kongresse und Tagungen im Zentrum — mit einem Empfang, der in Erinnerung bleibt.' },
      { n: 'Volkswagen Halle', d: 'Große Firmenevents und Shows — Ludwig hält auch vor tausend Gästen Hof.' },
      { n: 'Forschungs- & Mobilitätsevents', d: 'DLR, PTB, TU: Wo an autonomen Systemen geforscht wird, ist Ludwig Fachbesuch.' },
      { n: 'Burgplatz & historische Kulisse', d: 'Empfänge zwischen Dom und Löwenstandbild — der neue König der Löwenstadt.' },
    ],
    faqLoc: 'Stadthalle, Volkswagen Halle, Forschungscampus-Locations und historische Säle der Innenstadt. Ludwig benötigt nur ebene Fläche, Strom und Internet.',
    nearby: ['hannover', 'berlin', 'leipzig'],
  },
  {
    slug: 'kiel', name: 'Kiel', state: 'Schleswig-Holstein', pop: '250.000',
    intro: 'Sailing City, Kieler Woche, maritime Hightech: Kiel feiert das größte Sommerfest Nordeuropas — und weiß, wie man Menschenmengen begeistert. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Kongresse und Firmenevents in Kiel.',
    scene: 'Zur Kieler Woche strömen Millionen an die Förde — für Marken eine der größten Bühnen des Nordens. Ganzjährig tagen Unternehmen und Verbände im Ostseekai und in der Halle400, die maritime Wirtschaft von thyssenkrupp Marine Systems bis zur Ozeanforschung des GEOMAR prägt eine Stadt, die Hochtechnologie gewohnt ist. Ein König-Roboter mit frischer Brise um den Umhang: Ludwig macht Ihren Auftritt an der Förde zum Fotomotiv des Tages.',
    venues: [
      { n: 'Kieler Woche & Förde-Events', d: 'Sponsoren-Areale und Markenauftritte beim größten Sommerfest Nordeuropas — Ludwig zieht die Menge.' },
      { n: 'Ostseekai & Halle400', d: 'Kongresse und Tagungen mit Fördeblick — königlicher Empfang inklusive.' },
      { n: 'Maritime Wirtschaft & Forschung', d: 'Werften, GEOMAR, Marine-Technik: Hightech-Publikum trifft humanoide Robotik.' },
      { n: 'Sparkassen-Arena', d: 'Große Firmenevents und Shows — der König besteht auch in Arena-Dimension.' },
    ],
    faqLoc: 'Ostseekai, Halle400, Sparkassen-Arena, Locations an der Kiellinie sowie Hotels und Werftgelände. Nötig sind ebene Fläche, Strom und Internet — Seeluft verträgt Ludwig gut, Regen weniger.',
    nearby: ['hamburg', 'bremen'],
  },
  {
    slug: 'chemnitz', name: 'Chemnitz', state: 'Sachsen', pop: '250.000',
    intro: 'Stadt der Moderne und Kulturhauptstadt Europas 2025: Chemnitz hat bewiesen, dass es große Bühnen bespielen kann. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Kongresse und Firmenevents in Chemnitz — Sachsens Maschinenbau-Herz.',
    scene: 'Chemnitz ist seit über 150 Jahren Maschinenbau-Stadt — heute forschen TU Chemnitz und Fraunhofer an Produktionstechnik und Robotik von morgen. In der Messe Chemnitz und im Carlowitz Congresscenter treffen sich Fachmessen und Tagungen, und das Kulturhauptstadtjahr 2025 hat der Stadt einen Eventkalender und ein Selbstbewusstsein hinterlassen, die nachwirken. Ein König-Roboter vor dem Karl-Marx-Monument — dieses Foto schreibt Ihre Marke ins kollektive Gedächtnis der Stadt.',
    venues: [
      { n: 'Messe Chemnitz', d: 'Fach- und Regionalmessen — Ludwig macht Ihren Stand zum Publikumsmagneten.' },
      { n: 'Carlowitz Congresscenter', d: 'Kongresse und Tagungen im Zentrum — mit royalem Auftakt.' },
      { n: 'Maschinenbau- & Industrie-Events', d: 'Werksjubiläen und Kundentage der sächsischen Industrie — Automation zum Anfassen.' },
      { n: 'Kulturhauptstadt-Locations', d: 'Vom Industriemuseum bis zur Hartmannfabrik — Kulissen mit Geschichte für Auftritte mit Zukunft.' },
    ],
    faqLoc: 'Messe Chemnitz, Carlowitz Congresscenter, Industriemuseum und weitere Kulturhauptstadt-Locations sowie Werksgelände der Region. Es genügen ebene Fläche, Strom und Internet.',
    nearby: ['dresden', 'leipzig', 'nuernberg'],
  },

  /* ---------------- ÖSTERREICH ---------------- */
  {
    slug: 'wien', name: 'Wien', state: 'Österreich', country: 'AT', pop: '2,0 Mio.',
    intro: 'Kaiserstadt, Kongress-Weltmeister, Heimat der Hofburg: Wien empfängt Majestäten seit Jahrhunderten — Ludwig II. reiht sich standesgemäß ein. Mieten Sie den humanoiden Event-Roboter für Messen, Kongresse und Firmenevents in Wien.',
    scene: 'Wien zählt seit Jahren zu den weltweit führenden Kongress-Destinationen: Das Austria Center Vienna ist Österreichs größtes Konferenzzentrum, die Messe Wien füllt den Kalender mit Fach- und Publikumsmessen, und von der Hofburg bis zur Marx Halle reicht ein Location-Angebot, das von Kaiserglanz bis Industrial-Chic alles bedient. Ein König-Roboter in der Stadt von Sisi und Franz Joseph — charmanter lässt sich Zukunftstechnik nicht inszenieren, und das Publikum aus aller Welt filmt begeistert mit.',
    venues: [
      { n: 'Austria Center Vienna', d: 'Österreichs größtes Kongresszentrum — Ludwig empfängt internationale Delegationen auf Deutsch und Englisch.' },
      { n: 'Messe Wien', d: 'Fach- und Publikumsmessen — der König-Roboter macht Ihren Stand zum Gesprächsthema.' },
      { n: 'Hofburg Vienna', d: 'Galas und Kongresse in kaiserlichen Sälen — ein König kehrt in die Hofburg zurück.' },
      { n: 'Marx Halle & moderne Locations', d: 'Tech-Events und Produktlaunches in Industriearchitektur — Kontrast, der Content produziert.' },
    ],
    faqLoc: 'Austria Center Vienna, Messe Wien, Hofburg, Marx Halle sowie Hotels und Eventlocations der ganzen Stadt. Ludwig braucht nur eine ebene Fläche, Strom und Internet — kaiserliches Ambiente ist willkommen, aber optional.',
    nearby: ['graz', 'linz', 'salzburg'],
  },
  {
    slug: 'graz', name: 'Graz', state: 'Österreich', country: 'AT', pop: '300.000',
    intro: 'UNESCO-Altstadt, Uni-Stadt, heimliche Tech-Hauptstadt der Steiermark: Graz verbindet Charme mit Ingenieurskunst. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Kongresse und Firmenevents in Graz.',
    scene: 'In der Messe Congress Graz und der Stadthalle treffen sich Fachmessen, Kongresse und Galas der Steiermark; TU Graz und ein starker Automotive-Cluster (AVL, Magna) prägen ein Publikum, das Technik lebt. Ein humanoider Roboter, der zwischen Uhrturm-Blick und Messehalle Hof hält, liefert Graz genau die Geschichte, die geteilt wird — vom Studierenden-Event bis zum Zulieferer-Kongress.',
    venues: [
      { n: 'Messe Congress Graz', d: 'Messen und Kongresse der Steiermark — Ludwig macht Ihren Auftritt zum Publikumsmagneten.' },
      { n: 'Stadthalle Graz', d: 'Galas und Großevents — königlicher Empfang vor großer Kulisse.' },
      { n: 'Automotive- & Tech-Events', d: 'AVL, Magna & TU Graz: Robotik zum Anfassen für ein Publikum vom Fach.' },
      { n: 'Altstadt & Schloßberg-Locations', d: 'Empfänge und Feiern mit UNESCO-Kulisse — Geschichte trifft Zukunft.' },
    ],
    faqLoc: 'Messe Congress Graz, Stadthalle, Hotels und historische Locations der Altstadt sowie Firmengelände des steirischen Automotive-Clusters. Nötig sind ebene Fläche, Strom und Internet.',
    nearby: ['wien', 'linz', 'salzburg'],
  },
  {
    slug: 'linz', name: 'Linz', state: 'Österreich', country: 'AT', pop: '210.000',
    intro: 'Stadt der Ars Electronica: Nirgendwo in Österreich ist das Publikum vertrauter mit KI und Robotik als in Linz. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Kongresse und Firmenevents in Linz — Kunst trifft Maschine.',
    scene: 'Linz trägt den Titel UNESCO City of Media Arts und feiert mit dem Ars Electronica Festival jedes Jahr die Schnittstelle von Technologie und Gesellschaft — ein humanoider König-Roboter ist hier weniger Attraktion als Diskussionsbeitrag. Im Design Center tagen Kongresse und Messen, die Tabakfabrik beherbergt die Kreativ- und Startup-Szene, und die Industrie von voestalpine bis Software-Cluster liefert ein B2B-Publikum mit echtem Technikverständnis.',
    venues: [
      { n: 'Design Center Linz', d: 'Kongresse und Messen unter dem Glasdach — Ludwig empfängt, eröffnet und begeistert.' },
      { n: 'Tabakfabrik', d: 'Startup- und Kreativ-Events in Industriearchitektur — der König im Innovationsquartier.' },
      { n: 'Ars-Electronica-Umfeld', d: 'Medienkunst- und Tech-Formate — ein Roboter, der selbst zum Exponat taugt.' },
      { n: 'Industrie- & Konzernevents', d: 'voestalpine bis IT-Cluster: Werksjubiläen und Kundentage mit Zukunftsbotschaft.' },
    ],
    faqLoc: 'Design Center, Tabakfabrik, Brucknerhaus, Hotels und Werksgelände der Region. Es genügen ebene Fläche, Strom und Internetzugang.',
    nearby: ['wien', 'salzburg', 'graz'],
  },
  {
    slug: 'salzburg', name: 'Salzburg', state: 'Österreich', country: 'AT', pop: '160.000',
    intro: 'Festspielstadt, Mozart-Kulisse, Premium-Destination: Salzburg beherrscht die große Inszenierung wie kaum eine zweite Stadt. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Kongresse, Galas und Firmenevents in Salzburg.',
    scene: 'Im Messezentrum Salzburg und im Salzburg Congress treffen sich Fachmessen und internationale Tagungen, während die Stadt mit Festung, Altstadt und Festspielhäusern Kulissen bietet, die jedes Event veredeln. Salzburgs Eventpublikum ist anspruchsvoll und international — genau die Bühne für einen König-Roboter, der auf Deutsch und Englisch parliert und vor barocker Kulisse Bilder liefert, die um die Welt gehen.',
    venues: [
      { n: 'Messezentrum Salzburg', d: 'Fach- und Publikumsmessen — Ludwig macht Ihren Stand zur Hauptattraktion.' },
      { n: 'Salzburg Congress', d: 'Internationale Tagungen — königlicher Empfang für internationales Publikum.' },
      { n: 'Altstadt & Festungs-Locations', d: 'Galas und Empfänge vor Weltkulturerbe-Kulisse — barocker Rahmen, futuristischer Gast.' },
      { n: 'Premium-Hotels & Feiern', d: 'Exklusive Feiern und Incentives — der König reist standesgemäß an.' },
    ],
    faqLoc: 'Messezentrum Salzburg, Salzburg Congress, Hotels und historische Säle der Altstadt. Ludwig benötigt lediglich ebene Fläche, Strom und Internet.',
    nearby: ['muenchen', 'linz', 'innsbruck', 'wien'],
  },
  {
    slug: 'innsbruck', name: 'Innsbruck', state: 'Österreich', country: 'AT', pop: '130.000',
    intro: 'Alpenmetropole mit Kaiser-Geschichte: Unter dem Goldenen Dachl residierte einst Kaiser Maximilian — jetzt hält Ludwig II. Einzug. Mieten Sie den humanoiden Event-Roboter für Kongresse, Messen und Events in Innsbruck.',
    scene: 'Das Congress Innsbruck und die Messe Innsbruck bündeln Tagungen, Fachmessen und Alpin-Events einer Region, die von Tourismus, Sport und einer wachsenden Tech-Szene lebt. Innsbrucks Mischung aus alpiner Kulisse und urbanem Publikum ist ideal für Auftritte mit Postkarten-Potenzial: ein König-Roboter vor Bergpanorama — dieses Motiv gewinnt jeden Feed.',
    venues: [
      { n: 'Congress Innsbruck', d: 'Internationale Tagungen im Zentrum — Ludwig empfängt auf Deutsch und Englisch.' },
      { n: 'Messe Innsbruck', d: 'Fach- und Publikumsmessen — der König-Roboter zieht die Besucherströme.' },
      { n: 'Alpine Event-Locations', d: 'Incentives und Feiern mit Bergkulisse — futuristischer Gast, alpines Panorama.' },
      { n: 'Altstadt & Goldenes Dachl', d: 'Empfänge in der Kaiserstadt — von Maximilian zu Ludwig, die royale Linie hält.' },
    ],
    faqLoc: 'Congress und Messe Innsbruck, Hotels, Altstadt-Locations und alpine Eventflächen (witterungsabhängig). Nötig sind ebene Fläche, Strom und Internet.',
    nearby: ['muenchen', 'salzburg', 'zuerich'],
  },

  /* ---------------- SCHWEIZ ---------------- */
  {
    slug: 'zuerich', name: 'Zürich', state: 'Schweiz', country: 'CH', pop: '440.000',
    intro: 'Finanzplatz, ETH-Stadt, Robotik-Weltspitze: In Zürich wird an den humanoiden Robotern von morgen geforscht — Zeit, dass einer Hof hält. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Kongresse und Firmenevents in Zürich.',
    scene: 'Die ETH Zürich gehört in der Robotik zur Weltspitze, Banken und Versicherungen laden zu Kundenevents auf höchstem Niveau, und von der Messe Zürich über das Kongresshaus am See bis zum Circle am Flughafen reicht ein dichtes Netz erstklassiger Locations. Zürcher Publikum ist verwöhnt — und genau deshalb wirkt ein König-Roboter hier so stark: kein Gadget, sondern ein Charakter, der Konversation auf Deutsch und Englisch führt und jedem Anlass eine Geschichte gibt.',
    venues: [
      { n: 'Messe Zürich & Hallenstadion', d: 'Messen und Grossevents in Oerlikon — Ludwig macht Ihren Auftritt zum Stadtgespräch.' },
      { n: 'Kongresshaus Zürich', d: 'Kongresse und Galas am See — königlicher Empfang mit Alpenblick.' },
      { n: 'The Circle & Flughafen-Events', d: 'Internationale Launches und Konferenzen — mehrsprachig und planbar.' },
      { n: 'Banken- & Versicherungsevents', d: 'Kundenanlässe der Finanzbranche — Innovation, die Hände schüttelt.' },
    ],
    faqLoc: 'Messe Zürich, Hallenstadion, Kongresshaus, The Circle sowie Hotels und Eventlocations an der Bahnhofstrasse und am See. Voraussetzungen: ebene Fläche, Strom, Internet.',
    nearby: ['basel', 'bern', 'luzern'],
  },
  {
    slug: 'basel', name: 'Basel', state: 'Schweiz', country: 'CH', pop: '180.000',
    intro: 'Art Basel, Pharma-Welthauptstadt, Messestadt seit 1471: Basel weiß, wie man Weltpublikum empfängt. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Kongresse und Firmenevents in Basel.',
    scene: 'Die Messe Basel empfängt mit der Art Basel jährlich die globale Kunstwelt, das Congress Center Basel füllt den Kalender mit internationalen Kongressen, und Roche und Novartis machen die Stadt zum Zentrum der Life-Sciences. Ein humanoider Roboter trifft hier auf ein Publikum, das zwischen Kunst und Wissenschaft zu Hause ist — und einen Auftritt zu schätzen weiß, der beides verbindet: Präzision im Betrieb, Inszenierung im Charakter.',
    venues: [
      { n: 'Messe Basel', d: 'Weltmessen und Fachformate — Ludwig macht Ihren Stand zum meistfotografierten Ort der Halle.' },
      { n: 'Congress Center Basel', d: 'Internationale Kongresse — königlicher Empfang für Gäste aus aller Welt.' },
      { n: 'Pharma- & Life-Science-Events', d: 'Kundenanlässe und Jubiläen der Branche — Zukunftstechnik als Erlebnis.' },
      { n: 'Rheinufer & Kultur-Locations', d: 'Galas und Feiern zwischen Münster und Rhein — Kontrastprogramm mit Krone.' },
    ],
    faqLoc: 'Messe und Congress Center Basel, Hotels, Kultur-Locations und Firmenstandorte der Life-Science-Branche. Es genügen ebene Fläche, Strom und Internet.',
    nearby: ['zuerich', 'bern', 'luzern'],
  },
  {
    slug: 'bern', name: 'Bern', state: 'Schweiz', country: 'CH', pop: '145.000',
    intro: 'Bundesstadt, UNESCO-Altstadt, Zentrum der Schweizer Politik: Bern empfängt Delegationen aus aller Welt — und jetzt auch einen König. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Kongresse, Messen und Events in Bern.',
    scene: 'Auf dem BERNEXPO-Gelände treffen sich Messen und Kongresse der Hauptstadtregion, der Kursaal Bern verbindet Tagung und Gala mit Blick auf die Alpen, und zwischen Bundeshaus und Zytglogge feiert eine Stadt, die Repräsentation im Blut hat. Ein König-Roboter in der Bundesstadt: diplomatisch im Ton, präzise im Ablauf — und garantiert das meistdiskutierte Traktandum des Abends.',
    venues: [
      { n: 'BERNEXPO', d: 'Messen und Kongresse der Hauptstadtregion — Ludwig zieht die Besucherströme an Ihren Stand.' },
      { n: 'Kursaal Bern', d: 'Tagungen und Galas mit Alpenblick — königlicher Empfang inklusive.' },
      { n: 'Verbands- & Politik-Events', d: 'Anlässe im Umfeld der Bundesstadt — ein Gast, der Protokoll beherrscht.' },
      { n: 'UNESCO-Altstadt', d: 'Empfänge und Feiern zwischen Lauben und Zytglogge — Weltkulturerbe trifft Zukunft.' },
    ],
    faqLoc: 'BERNEXPO, Kursaal, Hotels und historische Säle der Altstadt. Ludwig benötigt nur eine ebene Fläche, Strom und Internet.',
    nearby: ['zuerich', 'basel', 'luzern', 'genf'],
  },
  {
    slug: 'genf', name: 'Genf', state: 'Schweiz', country: 'CH', pop: '205.000',
    intro: 'UNO-Stadt, Uhren-Metropole, internationalstes Parkett der Schweiz: In Genf zählt der perfekte Auftritt. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Messen, Kongresse und Premium-Events in Genf — auf Deutsch, Englisch und mit königlicher Etikette.',
    scene: 'Im Palexpo treffen sich Weltmessen von Watches & Wonders bis zu internationalen Fachsalons, das CICG empfängt Kongresse im Umfeld von UNO und NGOs, und die Uhren- und Luxusbranche setzt Massstäbe für Inszenierung. Genfs Publikum ist so international wie nirgendwo sonst im Land — ein humanoider König, der mehrsprachig empfängt und Präzision verkörpert, passt in die Stadt der Haute Horlogerie wie ein Tourbillon ins Uhrwerk.',
    venues: [
      { n: 'Palexpo', d: 'Weltmessen und Salons — Ludwig macht Ihren Stand zum Pflichttermin.' },
      { n: 'CICG', d: 'Internationale Kongresse im UNO-Umfeld — Empfang mit diplomatischer Klasse.' },
      { n: 'Uhren- & Luxus-Events', d: 'Launches und Private Views der Luxusbranche — Präzision trifft Präzision.' },
      { n: 'Seepromenade & Grandhotels', d: 'Galas mit Jet d’eau-Blick — der König residiert standesgemäß.' },
    ],
    faqLoc: 'Palexpo, CICG, Grandhotels an der Seepromenade und Locations der Luxusbranche. Voraussetzungen: ebene Fläche, Strom, Internet — Französisch-Basics bringt Ludwig charmant unter.',
    nearby: ['bern', 'zuerich', 'basel'],
  },
  {
    slug: 'luzern', name: 'Luzern', state: 'Schweiz', country: 'CH', pop: '85.000',
    intro: 'KKL, Kapellbrücke, Vierwaldstättersee: Luzern ist die Bühne der Schweiz — Kongresse mit Weltklasse-Akustik, Feiern mit Postkarten-Panorama. Mieten Sie Ludwig II., den humanoiden Event-Roboter, für Kongresse, Incentives und Events in Luzern.',
    scene: 'Das KKL Luzern gehört zu den renommiertesten Kongress- und Konzerthäusern Europas — wer hier einlädt, verspricht Weltklasse. Dazu kommen die Messe Luzern, Incentive-Programme internationaler Konzerne und eine Tourismusregion, die grosse Auftritte gewohnt ist. Ein König-Roboter vor der Kulisse von See und Pilatus liefert das Motiv, das jede Eventdokumentation adelt — und im KKL-Foyer wird die Audienz zum Programmpunkt, über den noch beim Apéro gesprochen wird.',
    venues: [
      { n: 'KKL Luzern', d: 'Kongresse und Galas im Weltklasse-Haus — königlicher Empfang im Foyer.' },
      { n: 'Messe Luzern', d: 'Fach- und Publikumsmessen der Zentralschweiz — Ludwig zieht die Besucherströme.' },
      { n: 'Incentives & Seelocations', d: 'Internationale Gäste, Schifffahrten, Panorama-Events — der König reist mit.' },
      { n: 'Grandhotels', d: 'Exklusive Feiern mit Belle-Époque-Charme — Zukunftstechnik im historischen Rahmen.' },
    ],
    faqLoc: 'KKL Luzern, Messe Luzern, Grandhotels und Seelocations (witterungsabhängig). Es genügen ebene Fläche, Strom und Internet.',
    nearby: ['zuerich', 'bern', 'basel'],
  },
];
