/* ============================================================
   Anlass-Daten für die SEO-Landingpages (/event-roboter/<slug>/).
   8 Buchungsanlässe. Pro Anlass UNIQUE Content:
   h1 (mit <em>), intro (Hero-Lead), scene (Szenario-Absatz),
   formats (Programmbausteine), faq, posts (Blog-Links),
   cities (Stadt-Links für die Crossverlinkung).
   Generator: tools/seo/generate.mjs
   ============================================================ */
export const OCCASIONS = [
  {
    slug: 'messe',
    name: 'Messe & Kongress',
    linkLabel: 'Messe-Roboter',
    h1: '<em>Messe-Roboter</em> mieten — der Standmagnet, der Besucherströme umlenkt',
    kicker: 'Anlass · Messen & Kongresse',
    title: 'Messe-Roboter mieten: humanoider Roboter als Standmagnet für Ihren Messestand',
    metaDesc: 'Messe-Roboter mieten: Humanoider Roboter Ludwig II. (Unitree G1) zieht Besucher an Ihren Messestand — mit Operator, versichert, deutschlandweit. Ab 2.500 € zzgl. USt.',
    intro: 'Zwischen hunderten Ständen entscheiden Sekunden, ob Besucher stehen bleiben oder weitergehen. Ein humanoider Roboter mit Krone und Umhang stoppt Laufwege zuverlässiger als jedes Give-away — und Ihr Standpersonal übernimmt die Gespräche, die er eröffnet.',
    scene: 'Der Ablauf ist auf Messen immer derselbe: Ludwig II. hält vor Ihrem Stand Hof, begrüßt Besucher auf Deutsch oder Englisch, posiert für Fotos und verwickelt das Publikum in Small Talk mit königlichem Augenzwinkern. Es bildet sich eine Traube — und eine Traube zieht die nächste an. Ihr Team steht daneben und macht aus Neugier Leads: Badge-Scans, Gespräche, Termine. Nach dem Einsatz bleibt der Auftritt in den Feeds der Besucher, denn kaum jemand geht an einem königlichen Roboter vorbei, ohne zu filmen.',
    formats: [
      { n: 'Standmagnet & Empfang', d: 'Ludwig hält vor oder auf Ihrem Stand Hof, begrüßt Besucher und stoppt Laufkundschaft — Ihr Team übernimmt das Fachgespräch.' },
      { n: 'Lead-Generierung', d: 'Der Roboter eröffnet Gespräche spielerisch; Badge-Scan oder Kontaktaufnahme passieren nebenbei — ohne Kaltakquise-Gefühl.' },
      { n: 'Fototermine & Content', d: 'Foto- und Videomomente mit Krone: Besucher teilen den Stand von selbst, auf Wunsch liefern wir Content-Aufnahmen fürs eigene Marketing.' },
      { n: 'Rundgänge über die Fläche', d: 'Begleitete Walkabouts über den Gang — Aufmerksamkeit dort abholen, wo sie läuft, und zum Stand zurückführen.' },
    ],
    faq: [
      { q: 'Was bringt ein Roboter am Messestand konkret?', a: 'Frequenz und Gesprächsanlässe: Ein humanoider Roboter stoppt Laufkundschaft, erzeugt Trauben vor dem Stand und eröffnet Gespräche, die Ihr Team in Leads verwandelt. Dazu kommen Foto- und Videomomente, die den Stand über die Messe hinaus sichtbar machen.' },
      { q: 'Was kostet ein Messe-Roboter pro Tag?', a: 'Einsätze beginnen ab 2.500 € zzgl. USt. für ein kompaktes Format ab ca. 2 Stunden. Ganze Messetage kalkulieren wir individuell — inklusive Operator, Anreise, Aufbau, Akkuwechsel-Planung und versichertem Betrieb.' },
      { q: 'Wie lange kann der Roboter am Stück laufen?', a: 'Der Akku hält 1,5–2 Stunden aktiven Betrieb; Wechsel dauern nur wenige Minuten und werden als kurze Pausen in den Messetag eingeplant. So ist Ludwig über den ganzen Tag präsent.' },
      { q: 'Braucht der Roboter viel Platz am Stand?', a: 'Nein — eine ebene Fläche von wenigen Quadratmetern, Strom und Internet genügen. Ablauf und Laufwege stimmen wir vorab mit Ihrem Standkonzept ab; auch Gang-Walkabouts sind nach Absprache mit der Messe möglich.' },
      { q: 'Auf welchen Messen ist ein Einsatz möglich?', a: 'Deutschlandweit auf allen Messeplätzen — von Hannover, Frankfurt und München über Köln und Düsseldorf bis Berlin, Hamburg, Leipzig, Nürnberg und Stuttgart. Auch Österreich und die Schweiz sind möglich.' },
    ],
    posts: ['roboter-auf-messen-standmagnet', 'humanoiden-roboter-mieten-kosten', 'roboter-event-planen-checkliste'],
    cities: ['hannover', 'frankfurt-am-main', 'koeln', 'duesseldorf', 'muenchen', 'berlin', 'nuernberg', 'leipzig'],
  },
  {
    slug: 'konferenz',
    name: 'Konferenz & Tagung',
    linkLabel: 'Konferenz-Roboter',
    h1: 'Roboter für <em>Konferenzen & Tagungen</em> — der Eröffnungsmoment, über den alle reden',
    kicker: 'Anlass · Konferenzen & Tagungen',
    title: 'Roboter für Konferenzen & Tagungen mieten: Keynote-Opening & Foyer-Highlight',
    metaDesc: 'Roboter für Konferenzen mieten: humanoider Event-Roboter für Keynote-Openings, Empfang & Pausen-Highlights. Mit Operator, Deutsch & Englisch, ab 2.500 € zzgl. USt.',
    intro: 'Konferenzen kämpfen um Aufmerksamkeit — im Saal, im Foyer und danach im Netz. Ein humanoider Roboter, der die Keynote eröffnet oder Gäste am Empfang begrüßt, gibt Ihrer Veranstaltung den Moment, den Teilnehmer noch Wochen später erzählen.',
    scene: 'Der König betritt die Bühne, das Saallicht geht an, die Smartphones gehen hoch: Ein Keynote-Opening mit Ludwig II. verwandelt den Pflichttermin in ein Ereignis. Davor oder danach hält er im Foyer Hof — begrüßt Teilnehmer beim Einlass, überbrückt Kaffeepausen und liefert das Gesprächsthema fürs Networking gleich mit. Moderierte Q&A-Momente, ein gemeinsamer Auftritt mit Ihrem CEO oder die Übergabe eines Awards: Das Drehbuch entsteht gemeinsam mit Ihrem Team.',
    formats: [
      { n: 'Keynote-Opening', d: 'Ludwig eröffnet die Bühne — allein oder im Doppel mit Ihrer Moderation. Ein Einstieg, der den Saal sofort wach macht.' },
      { n: 'Empfang & Einlass', d: 'Begrüßung der Teilnehmer am Eingang: Der erste Eindruck Ihrer Konferenz ist königlich — und wird fotografiert.' },
      { n: 'Pausen-Highlight im Foyer', d: 'Kaffeepausen werden zum Programmpunkt: Meet & Greet, Fotos, Small Talk auf Deutsch und Englisch.' },
      { n: 'Award-Übergabe & Bühnenmomente', d: 'Preisverleihungen, Jubiläums-Momente, Überraschungsauftritte — choreografiert und mit Ihrem Ablauf verzahnt.' },
    ],
    faq: [
      { q: 'Wie läuft ein Keynote-Opening mit dem Roboter ab?', a: 'Ablauf, Texte und Timing werden vorab mit Ihrer Regie abgestimmt. Ludwig betritt die Bühne, eröffnet mit einem kurzen, humorvollen Part und übergibt an Ihre Moderation — auf Wunsch mit gemeinsamem Dialog oder Q&A-Moment.' },
      { q: 'Spricht der Roboter auch Englisch für internationale Konferenzen?', a: 'Ja — Ludwig interagiert live auf Deutsch und Englisch und wechselt fliegend. Ideal für internationales Publikum; weitere Sprachen sind auf Anfrage möglich.' },
      { q: 'Was kostet ein Roboter-Auftritt auf einer Konferenz?', a: 'Ab 2.500 € zzgl. USt. für ein kompaktes Format ab ca. 2 Stunden — etwa Opening plus Foyer-Präsenz in der Pause. Ganztägige Begleitung kalkulieren wir individuell.' },
      { q: 'Funktioniert das auch in Hotels und Kongresszentren?', a: 'Ja. Kongresszentren, Tagungshotels, Eventlocations — nötig sind nur eine ebene Fläche, Strom und Internet. Technik-Check und Sicherheitskonzept sind Teil jeder Buchung.' },
      { q: 'Wie viel Vorlauf braucht die Planung?', a: 'Für abgestimmte Bühnenmomente empfehlen wir 2–4 Wochen Vorlauf. Kurzfristige Anfragen versuchen wir möglich zu machen — fragen Sie einfach mit Datum und Ort an.' },
    ],
    posts: ['event-roboter-ideen-konferenzen', 'roboter-event-planen-checkliste', 'unitree-g1-event-einsatz'],
    cities: ['berlin', 'frankfurt-am-main', 'muenchen', 'hamburg', 'koeln', 'stuttgart', 'leipzig', 'bonn'],
  },
  {
    slug: 'firmenfeier',
    name: 'Firmenfeier & Sommerfest',
    linkLabel: 'Roboter für Firmenfeiern',
    h1: 'Roboter für die <em>Firmenfeier</em> mieten — Hofstaat trifft Belegschaft',
    kicker: 'Anlass · Firmenfeiern & Jubiläen',
    title: 'Roboter für Firmenfeier, Sommerfest & Jubiläum mieten — das Highlight fürs Team',
    metaDesc: 'Roboter für Firmenfeier mieten: humanoider Event-Roboter für Sommerfest, Jubiläum & Betriebsfeier. Begrüßung, Show & Fotos — mit Operator, ab 2.500 € zzgl. USt.',
    intro: 'Das Team hat Programm verdient, nicht nur Buffet: Ein humanoider Roboter, der Kolleginnen und Kollegen begrüßt, Witze macht und für Fotos posiert, ist der Auftritt, über den noch beim nächsten Sommerfest gesprochen wird.',
    scene: 'Firmenfeiern leben von gemeinsamen Momenten — und Ludwig II. liefert sie im Minutentakt. Er empfängt die Belegschaft am Eingang, gratuliert zum Jubiläum, überreicht Auszeichnungen an verdiente Mitarbeiter oder eröffnet das Buffet per königlichem Dekret. Zwischen den Programmpunkten hält er Hof: Selfies, Small Talk, kleine Challenges. Das funktioniert im Innenhof genauso wie in der Eventlocation oder im Betriebsrestaurant — und verbindet Abteilungen, die sonst wenig miteinander reden.',
    formats: [
      { n: 'Empfang & Begrüßung', d: 'Der König empfängt die Belegschaft — ein Auftakt, der sofort Fotos und Gesprächsstoff produziert.' },
      { n: 'Ehrungen & Jubiläums-Momente', d: 'Auszeichnungen, Dienstjubiläen, Danksagungen: mit königlicher Zeremonie statt Folienpräsentation.' },
      { n: 'Meet & Greet im Freien', d: 'Sommerfest im Hof oder Park? Ludwig läuft auf ebenen Außenflächen und hält unter freiem Himmel Hof.' },
      { n: 'Foto-Stationen & Team-Content', d: 'Selfie-Point mit Krone und Umhang — Erinnerungen fürs Intranet, Recruiting und die Team-Kanäle.' },
    ],
    faq: [
      { q: 'Eignet sich der Roboter auch für kleinere Firmenfeiern?', a: 'Ja — Ludwig funktioniert vom 30-Personen-Teamevent bis zur Betriebsfeier mit tausend Gästen. Format und Dauer werden auf Ihre Feier zugeschnitten; das kompakte Format ab ca. 2 Stunden beginnt bei 2.500 € zzgl. USt.' },
      { q: 'Kann der Roboter draußen auftreten, z. B. beim Sommerfest?', a: 'Ja, auf ebenen, trockenen Flächen — Innenhof, Terrasse, befestigte Wege. Bei Regen braucht es einen überdachten Bereich; Details klären wir bei der Planung.' },
      { q: 'Kann Ludwig Mitarbeiter ehren oder Preise übergeben?', a: 'Sehr gern — Ehrungen, Jubiläen und Award-Übergaben gehören zu den beliebtesten Programmpunkten. Namen und Ablauf stimmen wir vorab ab, den königlichen Ton bringt Ludwig mit.' },
      { q: 'Ist das auch für die Weihnachtsfeier buchbar?', a: 'Ja — für Weihnachtsfeiern gibt es ein eigenes Format mit festlichem Programm. Beliebte Dezember-Termine sind früh vergeben; wir empfehlen mehrere Wochen Vorlauf.' },
      { q: 'Was braucht die Location für den Einsatz?', a: 'Eine ebene Fläche, Strom und Internet — mehr nicht. Der Operator übernimmt Aufbau, Technik-Check und Betreuung von Anfang bis Ende; der Betrieb ist versichert.' },
    ],
    posts: ['humanoiden-roboter-mieten-kosten', 'roboter-event-planen-checkliste', 'unitree-g1-event-einsatz'],
    cities: ['muenchen', 'stuttgart', 'hamburg', 'dortmund', 'essen', 'hannover', 'nuernberg', 'bremen'],
  },
  {
    slug: 'weihnachtsfeier',
    name: 'Weihnachtsfeier',
    linkLabel: 'Roboter für Weihnachtsfeiern',
    h1: 'Roboter für die <em>Weihnachtsfeier</em> mieten — royaler Glanz statt Standard-Programm',
    kicker: 'Anlass · Weihnachtsfeiern',
    title: 'Roboter für Weihnachtsfeier mieten: das Highlight für Ihre Firmen-Weihnachtsfeier',
    metaDesc: 'Roboter für die Weihnachtsfeier mieten: humanoider Event-Roboter begrüßt, gratuliert & glänzt auf Ihrer Firmen-Weihnachtsfeier. Mit Operator, ab 2.500 € zzgl. USt.',
    intro: 'Jedes Jahr dieselbe Frage: Was machen wir dieses Mal? Ein König aus Metall, der Geschenke verlost, Reden hält und mit der Belegschaft anstößt (symbolisch — Öl bleibt im Schrank), beantwortet sie ein für alle Mal.',
    scene: 'Dezember, volle Kalender, hohe Erwartungen: Die Weihnachtsfeier ist die eine Feier des Jahres, bei der das Programm sitzen muss. Ludwig II. empfängt die Gäste im festlich erleuchteten Foyer, hält eine königliche Weihnachtsansprache mit Augenzwinkern, zieht die Gewinner der Tombola und posiert geduldig für Fotos vor dem Baum. Ob Gala-Dinner im Hotel, Feier in der Eventlocation oder Fest im eigenen Haus — der Auftritt wird auf Ihren Abend choreografiert und vom Operator durchgehend begleitet.',
    formats: [
      { n: 'Festlicher Empfang', d: 'Der König begrüßt die Gäste zur Weihnachtsfeier — ein Entrée, das sofort die Handys zückt.' },
      { n: 'Weihnachtsansprache', d: 'Eine königliche Rede mit Humor und Dank ans Team — abgestimmt mit Ihrer Geschäftsführung.' },
      { n: 'Tombola & Geschenke', d: 'Ludwig zieht Lose, verkündet Gewinner und übergibt Präsente — Zeremonie statt Zettelbox.' },
      { n: 'Foto-Momente am Baum', d: 'Krone trifft Christbaum: der Selfie-Point des Abends, Erinnerungen inklusive.' },
    ],
    faq: [
      { q: 'Wie früh muss ich für die Weihnachtsfeier buchen?', a: 'So früh wie möglich — Dezember-Termine, besonders Donnerstage und Freitage, sind regelmäßig Monate im Voraus vergeben. Anfragen ab September sichern die besten Termine; kurzfristig hilft Flexibilität beim Datum.' },
      { q: 'Was kostet der Roboter auf der Weihnachtsfeier?', a: 'Einsätze beginnen ab 2.500 € zzgl. USt. für ein kompaktes Format ab ca. 2 Stunden — inklusive Operator, Anreise, Aufbau und versichertem Betrieb. Abendbegleitungen mit mehreren Programmpunkten kalkulieren wir individuell.' },
      { q: 'Kann der Roboter unsere Tombola oder Geschenkübergabe übernehmen?', a: 'Ja — Losziehung, Gewinner-Verkündung und Übergabe sind beliebte Programmpunkte. Ablauf und Namen werden vorab abgestimmt, damit jede Pointe sitzt.' },
      { q: 'Funktioniert der Auftritt im Restaurant oder Hotel?', a: 'Ja, in den meisten Locations: nötig sind eine ebene Fläche, Strom und Internet. Enge Gastro-Räume prüfen wir vorab gemeinsam anhand von Fotos oder einem kurzen Call.' },
      { q: 'Gibt es das Programm auch zweisprachig?', a: 'Ja — Ansprache und Interaktion funktionieren auf Deutsch und Englisch, auch gemischt. Ideal für internationale Teams.' },
    ],
    posts: ['humanoiden-roboter-mieten-kosten', 'event-roboter-ideen-konferenzen', 'roboter-event-planen-checkliste'],
    cities: ['berlin', 'muenchen', 'hamburg', 'koeln', 'frankfurt-am-main', 'duesseldorf', 'stuttgart', 'leipzig'],
  },
  {
    slug: 'produktpraesentation',
    name: 'Produktlaunch & Präsentation',
    linkLabel: 'Roboter für Produktlaunches',
    h1: 'Roboter für <em>Produktlaunch & Präsentation</em> — Seine Majestät enthüllt',
    kicker: 'Anlass · Produktlaunches',
    title: 'Roboter für Produktpräsentation & Launch mieten: der Enthüllungsmoment mit Reichweite',
    metaDesc: 'Roboter für Produktlaunch mieten: humanoider Event-Roboter inszeniert Ihre Produktpräsentation — Enthüllung, Bühne, Content. Mit Operator, ab 2.500 € zzgl. USt.',
    intro: 'Ein Launch braucht einen Moment, den Kameras lieben. Wenn ein humanoider König das Tuch vom Produkt zieht, haben Sie ihn — auf der Bühne, im Showroom und anschließend in jedem Feed, der zählt.',
    scene: 'Produktpräsentationen scheitern selten am Produkt und oft an der Dramaturgie. Ludwig II. gibt Ihrem Launch eine: der königliche Einmarsch, die Anmoderation mit Augenzwinkern, der Countdown, die Enthüllung. Danach präsentiert er das Produkt gemeinsam mit Ihrem Team, beantwortet Publikumsfragen im Duett mit Ihren Experten und liefert die Bilder, die Presse und Social Media aufgreifen. Ob Messe-Premiere, Showroom-Event oder Presse-Termin: Das Drehbuch entsteht mit Ihnen — die Aufmerksamkeit bringt der König mit.',
    formats: [
      { n: 'Die Enthüllung', d: 'Countdown, Tuch, Applaus: Ludwig inszeniert den Reveal-Moment, den Ihr Produkt verdient.' },
      { n: 'Bühnen-Doppel mit Ihrem Team', d: 'Der König moderiert an, Ihr Produktteam übernimmt die Tiefe — ein Dialog, der Zuschauer hält.' },
      { n: 'Presse- & Influencer-Termine', d: 'Foto-Calls und kurze Interview-Momente mit dem Roboter — planbare Bilder für Medien und Creator.' },
      { n: 'Content-Produktion', d: 'Auf Wunsch entstehen beim Launch Clips und Fotos für Ihre Kanäle — abgestimmt auf Ihr Marketing.' },
    ],
    faq: [
      { q: 'Wie wird die Enthüllung mit dem Roboter choreografiert?', a: 'Wir entwickeln den Ablauf gemeinsam: Einmarsch, Anmoderation, Countdown, Reveal und Übergabe an Ihr Team werden mit Regie, Licht und Ton abgestimmt — inklusive Probe vor dem Event, wenn gewünscht.' },
      { q: 'Kann der Roboter unser Produkt namentlich vorstellen?', a: 'Ja — Texte, Produktname und Kernbotschaften werden vorab eingearbeitet. Ludwig präsentiert Ihr Produkt mit königlichem Ton, sachlich korrekt und markenkonform.' },
      { q: 'Eignet sich das für Presse-Events?', a: 'Sehr gut: Ein humanoider Roboter gibt Journalisten und Creators einen Bildanlass, der über die Pflichtmeldung hinausgeht. Foto-Calls und kurze O-Ton-Momente sind planbar.' },
      { q: 'Was kostet ein Launch-Auftritt?', a: 'Kompakte Formate beginnen ab 2.500 € zzgl. USt.; choreografierte Launches mit Probe, individuellen Texten und Content-Produktion kalkulieren wir nach Aufwand — immer als individuelles Angebot.' },
      { q: 'Geht das auch im kleinen Rahmen, z. B. im Showroom?', a: 'Ja — vom intimen Kunden-Event im Showroom bis zur großen Bühne. Wichtig sind nur ebene Fläche, Strom und Internet; alles Weitere passt sich Ihrem Format an.' },
    ],
    posts: ['event-roboter-ideen-konferenzen', 'unitree-g1-event-einsatz', 'humanoiden-roboter-mieten-kosten'],
    cities: ['muenchen', 'berlin', 'stuttgart', 'frankfurt-am-main', 'duesseldorf', 'hamburg', 'koeln', 'braunschweig'],
  },
  {
    slug: 'eroeffnung',
    name: 'Eröffnung & Store Opening',
    linkLabel: 'Roboter für Eröffnungen',
    h1: 'Roboter für <em>Eröffnungen</em> mieten — royales Store Opening mit Anziehungskraft',
    kicker: 'Anlass · Eröffnungen & Retail',
    title: 'Roboter für Eröffnung & Store Opening mieten: der Publikumsmagnet vor Ihrer Tür',
    metaDesc: 'Roboter für Eröffnung mieten: humanoider Event-Roboter macht Ihr Store Opening zum Stadtgespräch — Laufkundschaft stoppt, filmt, teilt. Ab 2.500 € zzgl. USt.',
    intro: 'Eine Eröffnung hat genau einen Versuch, zum Stadtgespräch zu werden. Ein König, der vor Ihrer Tür Hof hält, Bänder durchschneidet und Passanten begrüßt, sorgt dafür, dass dieser Versuch sitzt.',
    scene: 'Store Opening, Filialeröffnung, Showroom-Einweihung: Ludwig II. verwandelt den ersten Tag in ein Ereignis. Vor der Tür stoppt er Laufkundschaft — Passanten bleiben stehen, filmen, kommen näher und dann herein. Drinnen begrüßt er die ersten Kunden, durchschneidet das Band mit königlicher Geste und posiert an Ihrer Fototapete. Lokalpresse und Stadt-Influencer bekommen ein Motiv, das gedruckt und gepostet wird. So wird aus einer Adressänderung eine Geschichte, die sich im Viertel herumspricht.',
    formats: [
      { n: 'Banddurchschnitt & Zeremonie', d: 'Die Eröffnung als königlicher Akt — mit Dekret, Schere und dem Foto, das die Lokalpresse druckt.' },
      { n: 'Passanten-Stopper vor der Tür', d: 'Ludwig hält vor dem Eingang Hof und macht aus Vorbeigehenden Hereinkommende.' },
      { n: 'Kunden-Begrüßung im Store', d: 'Die ersten Gäste werden königlich empfangen — Selfies inklusive, Kauflaune folgt.' },
      { n: 'Lokal-PR & Social Content', d: 'Ein Bildanlass für Lokalmedien und City-Influencer; auf Wunsch mit Content-Aufnahmen für Ihre Kanäle.' },
    ],
    faq: [
      { q: 'Darf der Roboter vor dem Geschäft im öffentlichen Raum auftreten?', a: 'Direkt vor Ihrer Tür auf Privatfläche ist es unkompliziert; für Gehweg und öffentlichen Raum klären wir Anforderungen gemeinsam im Vorfeld. Der Operator ist durchgehend dabei, der Betrieb versichert.' },
      { q: 'Wie lange dauert ein Eröffnungs-Einsatz?', a: 'Beliebt sind 2–4 Stunden rund um den Eröffnungsmoment: Empfang der ersten Gäste, Zeremonie, Foto-Session. Das kompakte Format ab ca. 2 Stunden beginnt bei 2.500 € zzgl. USt.' },
      { q: 'Funktioniert das auch in kleinen Ladenflächen?', a: 'Ja — Ludwig braucht nur wenige Quadratmeter ebene Fläche. In engen Stores verlagern wir den Schwerpunkt nach draußen vor die Tür, wo die Laufkundschaft ist.' },
      { q: 'Können wir eigene Branding-Elemente einbinden?', a: 'Gern: Umhang-Details, abgestimmte Texte, Ihr Store-Name in der Begrüßung — Branding-Optionen besprechen wir im Angebot.' },
      { q: 'Lohnt sich das für eine Filialkette mit mehreren Eröffnungen?', a: 'Ja — für Roll-outs über mehrere Städte erstellen wir Staffelangebote mit einheitlichem Ablauf und lokaler Anpassung. Deutschlandweit, planbar, ein Ansprechpartner.' },
    ],
    posts: ['roboter-auf-messen-standmagnet', 'humanoiden-roboter-mieten-kosten', 'unitree-g1-event-einsatz'],
    cities: ['berlin', 'hamburg', 'muenchen', 'koeln', 'duesseldorf', 'stuttgart', 'frankfurt-am-main', 'leipzig'],
  },
  {
    slug: 'gala',
    name: 'Gala & Preisverleihung',
    linkLabel: 'Roboter für Galas',
    h1: 'Roboter für <em>Galas & Preisverleihungen</em> — Glanz, der in Erinnerung bleibt',
    kicker: 'Anlass · Galas & Awards',
    title: 'Roboter für Gala & Preisverleihung mieten: königliche Momente für Ihren Abend',
    metaDesc: 'Roboter für Gala mieten: humanoider Event-Roboter für Preisverleihungen, Galadinner & Abendveranstaltungen — Empfang, Laudatio, Award-Übergabe. Ab 2.500 € zzgl. USt.',
    intro: 'Abendgarderobe, Kristall, große Namen — und ein König aus Metall, der die Gewinner ehrt. Auf Galas und Preisverleihungen liefert Ludwig II. die Momente, die zwischen Dinner und Dessert in Erinnerung bleiben.',
    scene: 'Eine Gala lebt vom Rhythmus zwischen feierlich und überraschend. Ludwig II. beherrscht beides: Am roten Teppich empfängt er die Gäste und sammelt die ersten Blitzlichter ein. Im Saal übergibt er Awards, verliest Laudatios mit königlicher Würde und einem Augenzwinkern und begleitet die Höhepunkte des Abends. Zwischen den Gängen hält er Hof an den Tischen — ein Gesprächsanlass, der Tischnachbarn verbindet. Charity-Gala, Branchen-Award oder Jubiläums-Dinner: Der Auftritt fügt sich in Ihre Dramaturgie, statt sie zu dominieren.',
    formats: [
      { n: 'Roter Teppich & Empfang', d: 'Der König empfängt Ihre Gäste — das erste Foto des Abends entsteht schon am Eingang.' },
      { n: 'Award-Übergabe & Laudatio', d: 'Preise mit Zeremonie: Ludwig verliest, gratuliert und übergibt — abgestimmt mit Ihrer Regie.' },
      { n: 'Tisch-Besuche zwischen den Gängen', d: 'Small Talk in Abendgarderobe: Der Roboter besucht die Tische und wird zum Gesprächsthema des Dinners.' },
      { n: 'Charity-Momente', d: 'Versteigerungen, Spenden-Ankündigungen, Danksagungen — königlich inszeniert für den guten Zweck.' },
    ],
    faq: [
      { q: 'Passt ein Roboter zum feierlichen Rahmen einer Gala?', a: 'Ja — der Auftritt wird der Dramaturgie des Abends angepasst: würdevoll bei der Award-Übergabe, charmant beim Empfang, dezent zwischen den Gängen. Krone und Umhang fügen sich erstaunlich gut zwischen Smoking und Abendkleid.' },
      { q: 'Kann der Roboter Preisträger namentlich ehren?', a: 'Ja — Namen, Kategorien und Laudatio-Texte werden vorab eingearbeitet und mit Ihrer Regie abgestimmt, damit jede Übergabe präzise sitzt.' },
      { q: 'Wie fügt sich der Auftritt in unseren Abendablauf ein?', a: 'Flexibel: einzelne Programmpunkte (Empfang, Übergabe) oder Begleitung über den Abend. Timing wird mit Moderation, Technik und Küche koordiniert — der Operator hält Rücksprache mit Ihrer Regie.' },
      { q: 'Was kostet ein Gala-Einsatz?', a: 'Kompakte Formate beginnen ab 2.500 € zzgl. USt.; Abendbegleitungen mit mehreren choreografierten Momenten kalkulieren wir individuell — inklusive Operator, Anreise und versichertem Betrieb.' },
      { q: 'Ist der Roboter im Ballsaal-Licht gut zu sehen und zu hören?', a: 'Ja — Beleuchtung und Ton werden beim Technik-Check mit Ihrer Location abgestimmt; bei Bedarf wird Ludwig in Ihre Ton-Anlage eingebunden.' },
    ],
    posts: ['event-roboter-ideen-konferenzen', 'humanoiden-roboter-mieten-kosten', 'roboter-event-planen-checkliste'],
    cities: ['berlin', 'muenchen', 'hamburg', 'frankfurt-am-main', 'duesseldorf', 'koeln', 'dresden', 'wiesbaden'],
  },
  {
    slug: 'hochzeit',
    name: 'Hochzeit & private Feiern',
    linkLabel: 'Roboter für Hochzeiten',
    h1: 'Roboter für die <em>Hochzeit</em> mieten — der Überraschungsgast mit Krone',
    kicker: 'Anlass · Premium-Feiern & Hochzeiten',
    title: 'Roboter für Hochzeit mieten: humanoider Überraschungsgast für Premium-Feiern',
    metaDesc: 'Roboter für Hochzeit mieten: Ludwig II. gratuliert dem Brautpaar, führt Zeremonien-Momente an & sorgt für unvergessliche Fotos. Exklusiv, mit Operator, ab 2.500 €.',
    intro: 'Es gibt Hochzeitsüberraschungen — und es gibt einen König, der dem Brautpaar gratuliert. Für Feiern, bei denen „schön" nicht reicht, ist Ludwig II. der Gast, von dem noch die Enkel erzählen.',
    scene: 'Der Moment, in dem ein humanoider König den Saal betritt und dem Brautpaar mit einer Verbeugung gratuliert, gehört zu den Bildern, die eine Hochzeit unvergesslich machen. Ludwig eröffnet den Empfang, führt Gratulations-Momente an, hebt (symbolisch) das Glas auf das Paar und posiert für Fotos mit Gästen jeder Generation — Kinder lieben ihn, Großeltern fotografieren ihn. Wir arbeiten dabei eng mit Hochzeitsplanern und Locations zusammen: Der Auftritt wird diskret geplant, damit die Überraschung gelingt und der Ablauf des Tages ungestört bleibt.',
    formats: [
      { n: 'Gratulation ans Brautpaar', d: 'Der königliche Glückwunsch als Überraschungsmoment — mit Verbeugung, Rede und stehenden Ovationen.' },
      { n: 'Empfang der Hochzeitsgäste', d: 'Ludwig begrüßt die Gäste beim Sektempfang — der Eisbrecher zwischen beiden Familien.' },
      { n: 'Foto-Momente für alle Generationen', d: 'Vom Blumenkind bis zur Großmutter: Fotos mit dem König werden zum Familienschatz.' },
      { n: 'Zusammenarbeit mit Weddingplanern', d: 'Diskrete Planung mit Planer und Location — Timing, Überraschungseffekt und Ablauf aus einer Hand.' },
    ],
    faq: [
      { q: 'Wie läuft die Überraschung fürs Brautpaar ab?', a: 'Diskret: Wir stimmen uns mit Trauzeugen, Weddingplaner oder Location ab, Ludwig wird unbemerkt aufgebaut und betritt den Saal im vereinbarten Moment. Der Operator bleibt im Hintergrund, die Überraschung im Vordergrund.' },
      { q: 'Was kostet ein Roboter-Auftritt auf einer Hochzeit?', a: 'Einsätze beginnen ab 2.500 € zzgl. USt. für ein kompaktes Format ab ca. 2 Stunden — inklusive Operator, Anreise, Aufbau und versichertem Betrieb. Individuelle Programmwünsche kalkulieren wir im Angebot.' },
      { q: 'Kann Ludwig eine persönliche Rede für das Paar halten?', a: 'Ja — Namen, Anekdoten und persönliche Botschaften werden vorab vertraulich eingearbeitet. Die Rede hält Ludwig auf Deutsch oder Englisch, gern auch zweisprachig für internationale Familien.' },
      { q: 'Ist der Roboter auch für Verlobungen oder runde Geburtstage buchbar?', a: 'Ja — Premium-Feiern jeder Art: Verlobung, runder Geburtstag, Jahrestag. Der Rahmen ist derselbe: exklusives Format, diskrete Planung, königlicher Auftritt.' },
      { q: 'Stört der Roboter den Ablauf oder die Musik?', a: 'Nein — Auftrittsfenster werden mit DJ, Band und Fotografen abgestimmt. Ludwig fügt sich in den Zeitplan des Tages ein; der Operator koordiniert live mit Ihren Dienstleistern.' },
    ],
    posts: ['humanoiden-roboter-mieten-kosten', 'roboter-event-planen-checkliste', 'event-roboter-ideen-konferenzen'],
    cities: ['muenchen', 'hamburg', 'berlin', 'koeln', 'stuttgart', 'wiesbaden', 'bonn', 'muenster'],
  },
];
